/**
 * @file    bq25710.h
 * @brief   BQ25710 驱动程序 — 公共接口头文件
 * @author  Generated by File Agent
 * @version 2.0.0
 * @date    2026-06-11
 *
 * @details
 * 本文件声明 BQ25710 统一驱动程序的全部公共 API，覆盖以下 15 个功能模块：
 *
 * | 序号 | 模块          | 说明                                       |
 * |------|---------------|--------------------------------------------|
 * |  1   | 模式管理      | 运行时模式切换 (IDLE/CHARGING/OTG/PTM/...)  |
 * |  2   | 充电管理      | 7阶段状态机, Battery/TI profile 参数支持    |
 * |  3   | OTG 管理      | 反向输出 5V/9V/12V/15V/20V, 电压斜率       |
 * |  4   | 输入功率管理  | IDPM, VDPM, ILIM_HIZ, ICO, 两级峰值功率    |
 * |  5   | PTM 直通模式  | 适配器直通系统, 绕过开关损耗                |
 * |  6   | VAP 有源保护  | 电容储能抵御系统峰值, 保守模式              |
 * |  7   | PROCHOT 管理  | 9 源触发, 极性/脉宽/扩展, ISR 框架         |
 * |  8   | PSYS 功率监控 | 系统总功率输出, 功率预算管理                |
 * |  9   | 学习模式      | 充放电循环, 库仑计数, 容量估算              |
 * | 10   | ADC 监测      | 8 通道全量读取, 单次/连续模式, 动态增益     |
 * | 11   | 故障管理      | 综合故障检测, 清除, 详细描述, 自动恢复      |
 * | 12   | 看门狗管理    | 配置/喂狗/禁用                              |
 * | 13   | 自动检测      | 电池节数检测, 化学类型识别, 热插拔          |
 * | 14   | 系统信息      | 全寄存器 dump, 状态报告                     |
 * | 15   | 初始化/反初始化| SMBus 回调注入, 安全关闭                    |
 *
 * @copyright Copyright (c) 2026
 */

#ifndef BQ25710_H
#define BQ25710_H

#include <stdint.h>
#include "bq25710_abstraction.h"
#include "battery_ti.h"

#ifndef __BIT
#define __BIT(x) (1 << (x))
#endif

/**
 * @brief SMBus 读寄存器回调
 * @param reg   寄存器地址 (7-bit SMBus 命令码)
 * @param value 输出参数, 读取到的 16-bit 寄存器原始值
 * @return 0=成功, <0=错误码
 */
typedef int8_t (*bq25710_smbus_read_cb_t)(uint8_t reg, uint16_t *value);

/**
 * @brief SMBus 写寄存器回调
 * @param reg   寄存器地址 (7-bit SMBus 命令码)
 * @param value 要写入的 16-bit 寄存器原始值
 * @return 0=成功, <0=错误码
 */
typedef int8_t (*bq25710_smbus_write_cb_t)(uint8_t reg, uint16_t value);

/**
 * @brief 毫秒延时回调
 * @param ms 延时时长 (毫秒)
 */
typedef void (*bq25710_delay_ms_cb_t)(uint32_t ms);

/* =========================================================================
 * 错误码体系
 * ========================================================================= */

typedef enum {
    BQ25710_ERR_OK           =  0,   /**< 操作成功 */
    BQ25710_ERR_PARAM        = -1,   /**< 参数无效 (超出范围/格式错误) */
    BQ25710_ERR_I2C          = -2,   /**< SMBus/I2C 通信错误 */
    BQ25710_ERR_MODE         = -3,   /**< 模式切换非法 (当前状态不允许) */
    BQ25710_ERR_TIMEOUT      = -4,   /**< 操作超时 (充电/学习/ADC超时) */
    BQ25710_ERR_FAULT        = -5,   /**< 硬件故障触发, 操作被拒绝 */
    BQ25710_ERR_NOT_INIT     = -6,   /**< 驱动未初始化 */
    BQ25710_ERR_NULL_PTR     = -7,   /**< 空指针参数 */
    BQ25710_ERR_OTG_ACTIVE   = -8,   /**< OTG 模式下不允许当前操作 */
    BQ25710_ERR_BAT_MISSING  = -9,   /**< 电池不存在 */
    BQ25710_ERR_ADAPTER_MISS = -10,  /**< 适配器未接入 */
    BQ25710_ERR_DEVICE_ID    = -11,  /**< 器件 ID 不匹配 */
    BQ25710_ERR_STATE        = -12,  /**< 状态机状态不允许当前操作 */
} bq25710_err_t;

/* =========================================================================
 * 看门狗管理
 * ========================================================================= */

typedef enum {
    BQ25710_WDT_DISABLE  = 0b00,  // 禁用看门狗
    BQ25710_WDT_5S       = 0b01,  // 5 秒超时
    BQ25710_WDT_88S      = 0b10,  // 88 秒超时
    BQ25710_WDT_175S     = 0b11   // 175 秒超时
} bq25710_watchdog_t;

/* =========================================================================
 * 运行模式枚举
 * ========================================================================= */

typedef enum {
    BQ25710_MODE_IDLE          = 0,  /**< 空闲/待机 — 充电禁止, 功率路径自动管理 */
    BQ25710_MODE_CHARGING      = 1,  /**< 充电模式 — 电池充电状态机运行 */
    BQ25710_MODE_OTG           = 2,  /**< OTG 反向输出 — 电池 → VBUS 供电 */
    BQ25710_MODE_PTM           = 3,  /**< 直通模式 — 输入直通系统, 绕过开关损耗 */
    BQ25710_MODE_PEAK_POWER_L1 = 4,  /**< 峰值功率 Level1 — 适配器+电池联合供电 */
    BQ25710_MODE_PEAK_POWER_L2 = 5,  /**< 峰值功率 Level2 — 仅电池补偿供电 */
    BQ25710_MODE_LEARN         = 6,  /**< 学习模式 — 电池放电校准 */
    BQ25710_MODE_PASSTHROUGH   = 7,  /**< 纯旁路 — NVDC 功率路径自动管理 */
} bq25710_operation_mode_t;

/* =========================================================================
 * 电池参数枚举与配置   
 * ========================================================================= */

/** 充电阶段 */
typedef enum {
    BQ25710_CHG_STAGE_IDLE       = 0,  /**< 空闲 — 未开始充电 */
    BQ25710_CHG_STAGE_DETECTION  = 1,  /**< 检测 — 检测适配器/电池/通信 */
    BQ25710_CHG_STAGE_PRECHARGE  = 2,  /**< 预充电 — LDO 模式, 电池亏电 */
    BQ25710_CHG_STAGE_CC         = 3,  /**< 恒流快充 — 最大充电电流 */
    BQ25710_CHG_STAGE_CV         = 4,  /**< 恒压充电 — 电流逐渐下降 */
    BQ25710_CHG_STAGE_DONE       = 5,  /**< 充电完成 — C/10 终止 */
    BQ25710_CHG_STAGE_FAULT      = 6,  /**< 故障 — 检测到故障, 等待恢复 */
} bq25710_charge_stage_t;


/* =========================================================================
 * PROCHOT 触发源掩码
 * ========================================================================= */

/** PROCHOT 触发源位掩码 */
typedef enum {
    BQ25710_PROCHOT_SRC_ACOK    = __BIT(0),  /**< 适配器移除 (PP_ACOK) */
    BQ25710_PROCHOT_SRC_BATPRES = __BIT(1),  /**< 电池移除 (PP_BATPRES) */
    BQ25710_PROCHOT_SRC_VSYS    = __BIT(2),  /**< VSYS 欠压 (PP_VSYS) */
    BQ25710_PROCHOT_SRC_IDCHG   = __BIT(3),  /**< 电池放电过流 (PP_IDCHG) */
    BQ25710_PROCHOT_SRC_INOM    = __BIT(4),  /**< 输入平均过流 (PP_INOM) */
    BQ25710_PROCHOT_SRC_ICRIT   = __BIT(5),  /**< 输入峰值过流 (PP_ICRIT) */
    BQ25710_PROCHOT_SRC_COMP    = __BIT(6),  /**< 独立比较器 (PP_COMP) */
    BQ25710_PROCHOT_SRC_VDPM    = __BIT(7),  /**< VBUS 欠压 (PP_VDPM) */
    BQ25710_PROCHOT_SRC_VAP     = __BIT(8),  /**< VAP 退出/失败 (STAT_EXIT_VAP/STAT_VAP_FAIL) */
} bq25710_prochot_src_t;

#define BQ25710_PROCHOT_SRC_ALL  0x01FF   /**< 全部 9 个触发源掩码 */
#define BQ25710_PROCHOT_SRC_NONE 0x0000   /**< 无触发源 */

/** PROCHOT 引脚极性 */
typedef enum {
    BQ25710_PROCHOT_ACTIVE_LOW  = 0,  /**< 开漏输出, 低有效 (默认) */
    BQ25710_PROCHOT_ACTIVE_HIGH = 1,  /**< 推挽输出, 高有效 */
} bq25710_prochot_polarity_t;

/** PROCHOT 脉冲宽度 */
typedef enum {
    BQ25710_PROCHOT_WIDTH_100US = 0,  /**< 100 μs */
    BQ25710_PROCHOT_WIDTH_1MS   = 1,  /**< 1 ms */
    BQ25710_PROCHOT_WIDTH_10MS  = 2,  /**< 10 ms (默认) */
    BQ25710_PROCHOT_WIDTH_5MS   = 3,  /**< 5 ms */
} bq25710_prochot_width_t;

/** PROCHOT 输出模式 */
typedef enum {
    BQ25710_PROCHOT_MODE_PULSE    = 0,  /**< 脉冲模式 — 触发后自动释放 */
    BQ25710_PROCHOT_MODE_EXTENDED = 1,  /**< 扩展模式 — 保持低电平直到手动清除 */
} bq25710_prochot_output_mode_t;

/* =========================================================================
 * OTG 输出预设
 * ========================================================================= */

/** OTG 输出电压预设值 (mV) */
#define BQ25710_OTG_PRESET_5V   5000
#define BQ25710_OTG_PRESET_9V   9000
#define BQ25710_OTG_PRESET_12V  12000
#define BQ25710_OTG_PRESET_15V  15000
#define BQ25710_OTG_PRESET_20V  20000

/** OTG 输出电流预设值 (mA) — USB PD 3.0 典型档位 */
#define BQ25710_OTG_ICURR_500MA   500
#define BQ25710_OTG_ICURR_1500MA 1500
#define BQ25710_OTG_ICURR_3000MA 3000
#define BQ25710_OTG_ICURR_5000MA 5000

/* =========================================================================
 * ADC 数据缓存结构体 
 * ========================================================================= */

typedef struct {
    uint16_t vbus_mv;      /**< VBUS 电压 (mV), 范围 3200~19520 */
    int32_t  psys_mw;      /**< 系统总功率 (mW), 正数代表系统消耗 */
    int32_t  ichg_ma;      /**< 充电电流 (mA), 正数=充电, 受 IBAT_GAIN 影响 */
    int32_t  idchg_ma;     /**< 放电电流 (mA), 正数=放电, 受 IBAT_GAIN 影响 */
    int32_t  iin_ma;       /**< 输入电流 (mA), 受 IADPT_GAIN 影响 */
    uint16_t vsys_mv;      /**< 系统电压 (mV), 范围 2880~19200 */
    uint16_t vbat_mv;      /**< 电池电压 (mV), 范围 2880~19200 */
    uint16_t cmpin_mv;     /**< 独立比较器输入电压 (mV), 范围 0~3060 */
    uint32_t timestamp_ms; /**< 采样时间戳 (ms, 从驱动初始化起算) */
    uint8_t  ibat_gain;    /**< 本次采样时的 IBAT 增益 (0=16x, 1=8x) */
    uint8_t  iadpt_gain;   /**< 本次采样时的 IADPT 增益 (0=20x, 1=40x) */
} bq25710_adc_data_t;

/* =========================================================================
 * 故障掩码与描述结构体
 * ========================================================================= */

/** 故障标志位掩码  */
typedef struct {
    /* ChargerStatus 低字节 — 硬件故障锁存 */
    uint16_t otg_uvp     : 1;  /**< OTG 欠压 */
    uint16_t otg_ovp     : 1;  /**< OTG 过压 */
    uint16_t latch       : 1;  /**< 强制闭锁 (独立比较器触发) */
    uint16_t sys_short   : 1;  /**< 系统短路 (7 次重试失败) */
    uint16_t sysovp      : 1;  /**< 系统过压 */
    uint16_t acoc        : 1;  /**< 输入过流 */
    uint16_t batoc       : 1;  /**< 电池放电过流 */
    uint16_t acov        : 1;  /**< 输入过压 */

    /* ProchotStatus — PROCHOT 事件 */
    uint16_t prochot_adapter_removal : 1;  /**< PROCHOT: 适配器移除 */
    uint16_t prochot_battery_removal : 1;  /**< PROCHOT: 电池移除 */
    uint16_t prochot_vsys            : 1;  /**< PROCHOT: VSYS 欠压 */
    uint16_t prochot_idchg           : 1;  /**< PROCHOT: 电池放电过流 */
    uint16_t prochot_inom            : 1;  /**< PROCHOT: 输入平均过流 */
    uint16_t prochot_icrit           : 1;  /**< PROCHOT: 输入峰值过流 */
    uint16_t prochot_comp            : 1;  /**< PROCHOT: 独立比较器 */
    uint16_t prochot_vdpm            : 1;  /**< PROCHOT: VDPM */
    uint16_t prochot_vap_exit        : 1;  /**< PROCHOT: 退出 VAP */
    uint16_t prochot_vap_fail        : 1;  /**< PROCHOT: VAP 失败 */

    uint16_t reserved : 13;  /**< 保留 */
} bq25710_fault_mask_t;

/* =========================================================================
 * 9. 系统综合状态结构体
 * ========================================================================= */

typedef struct {
    /* 基础状态 */
    bq25710_operation_mode_t mode;                      /**< 当前运行模式 */
    bq25710_charge_stage_t   chg_stage;                 /**< 当前充电阶段 (仅 CHARGING 模式有效) */
    uint8_t                  adapter_present;           /**< 适配器是否接入 */
    uint8_t                  battery_present;           /**< 电池是否存在 */
    uint8_t                  is_charging;               /**< 是否处于充电中 (预充/快充) */
    uint8_t                  is_otg;                    /**< 是否处于 OTG 模式 */
    uint8_t                  is_vap;                    /**< 是否处于 VAP 模式 */
    uint8_t                  is_ptm;                    /**< 是否处于 PTM 模式 */
    uint8_t                  ico_done;                  /**< ICO 是否已完成 */

    /* 充电参数 */
    const battery_ti_bq25710_params_t *batt_params;     /**< 当前电池参数 */
    uint16_t                 charge_voltage_set_mv;     /**< 充电电压设定值 (mV) */
    uint16_t                 charge_current_set_ma;     /**< 充电电流设定值 (mA) */
    uint16_t                 input_current_limit_ma;    /**< 输入电流限制 (mA) */

    /* 实时 ADC 数据 */
    bq25710_adc_data_t       adc;                       /**< 最新 ADC 读数 */

    /* 故障状态 */
    bq25710_fault_mask_t     fault;                     /**< 当前故障掩码 */
    uint8_t                  fault_active;              /**< 是否有活动故障 */

    /* 运行统计 */
    uint32_t                 uptime_ms;                 /**< 驱动运行时间 (ms) */
    uint32_t                 chg_elapsed_ms;            /**< 本次充电已耗时 (ms) */
    uint32_t                 wdt_timeout_ms;            /**< 看门狗超时设置 (ms, 0=禁用) */
    uint32_t                 last_kick_ms;              /**< 上次喂狗时间戳 (ms) */

} bq25710_system_status_t;

/* =========================================================================
 * 充电上下文 (内部状态机使用)
 * ========================================================================= */

#define BQ25710_PRECHARGE_TIMEOUT_MS_DEFAULT    (30 * 60 * 1000)        /** 预充电默认超时时间 */
#define BQ25710_CC_TIMEOUT_MS_DEFAULT           (4 * 3600 * 1000)       /** CC 超时默认时间 */
#define BQ25710_CV_TIMEOUT_MS_DEFAULT           (2 * 3600 * 1000)       /** CV 超时默认时间 */

typedef struct {
    battery_ti_bq25710_params_t params;                 /**< 当前电池参数 */
    bq25710_charge_stage_t   stage;                     /**< 当前充电阶段 */
    battery_chemistry_t      chemistry;                 /**< 化学类型 */
    battery_cell_count_t     cells;                     /**< 节数 */
    uint32_t                 stage_start_ms;            /**< 当前阶段起始时间戳 */
    uint32_t                 total_elapsed_ms;          /**< 总充电耗时 */
    uint32_t                 wdt_kick_interval_ms;      /**< 喂狗间隔 */
    uint32_t                 last_wdt_kick_ms;          /**< 上次喂狗时间 */
    uint32_t                 precharge_timeout_ms;      /**< 预充电超时 (默认 30min) */
    uint32_t                 cc_timeout_ms;             /**< CC 超时 (默认 4h) */
    uint32_t                 cv_timeout_ms;             /**< CV 超时 (默认 2h) */
    uint8_t                  initialized;               /**< 是否已初始化 */
} bq25710_charge_ctx_t;

/* =========================================================================
 * 驱动主上下文
 * ========================================================================= */

typedef struct {
    uint8_t                   initialized;              /**< 驱动是否已初始化 */
    bq25710_operation_mode_t  mode;                     /**< 当前运行模式 */
    bq25710_operation_mode_t  prev_mode;                /**< 上一个运行模式 */

    /* SMBus 回调 */
    bq25710_smbus_read_cb_t   smbus_read;               /**< smbus 读寄存器回调 */
    bq25710_smbus_write_cb_t  smbus_write;              /**< smbus 写寄存器回调 */
    bq25710_delay_ms_cb_t     delay_ms;                 /**< 毫秒延时回调 */

    /* 各子系统上下文 */
    bq25710_charge_ctx_t      charge;                   /**< 充电状态机 */
    bq25710_adc_data_t        adc_cache;                /**< ADC 最新缓存 */
    bq25710_fault_mask_t      fault_cache;              /**< 故障最新缓存 */

    /* 看门狗 */
    uint32_t                  wdt_timeout_ms;           /**< 看门狗超时设置 (ms, 0=禁用) */
    uint32_t                  last_kick_ms;             /**< 上次喂狗时间戳 (ms) */

    /* PROCHOT */
    uint16_t                  prochot_trigger_mask;     /**< PROCHOT 触发掩码 */
    uint8_t                   prochot_extended_mode;    /**< PROCHOT 扩展模式 */

    /* 时间基准 */
    uint32_t                  tick_ms;                  /**< 时间基准 (ms) */
    uint8_t                   tick_valid;               /**< 时间基准是否有效 */

    /* 学习模式 */
    float                     learn_capacity_mah;       /**< 学习模式下已充电容量 (mAh) */
    uint8_t                   learn_complete;           /**< 学习模式是否完成 */

} bq25710_drv_ctx_t;

/** 全局驱动上下文指针 */
extern bq25710_drv_ctx_t g_bq25710_ctx;

/* =========================================================================
 * API 声明
 * ========================================================================= */

/* ---------- 初始化 / 反初始化 ---------- */

/**
 * @brief 初始化 BQ25710 全功能驱动
 * @param smbus_read   SMBus 读寄存器回调
 * @param smbus_write  SMBus 写寄存器回调
 * @param delay_ms     毫秒延时回调
 * @return BQ25710_ERR_OK 成功, 其他为错误码
 */
bq25710_err_t bq25710_init(bq25710_smbus_read_cb_t  smbus_read,
                            bq25710_smbus_write_cb_t smbus_write,
                            bq25710_delay_ms_cb_t    delay_ms);

/**
 * @brief  反初始化驱动, 安全关闭所有功能
 * @return BQ25710_ERR_OK 成功
 */
bq25710_err_t bq25710_deinit(void);

/* ---------- 模式管理 ---------- */

/**
 * @brief 切换运行模式
 * @details 内部执行安全序列: 停止当前模式 → 配置新模式的寄存器 → 启动新模式
 * @param mode 目标运行模式
 * @return BQ25710_ERR_OK / BQ25710_ERR_MODE (非法切换) / BQ25710_ERR_PARAM
 */
bq25710_err_t bq25710_set_mode(bq25710_operation_mode_t mode);

/**
 * @brief 获取当前运行模式
 * @return 当前运行模式枚举值
 */
bq25710_operation_mode_t bq25710_get_mode(void);

/**
 * @brief 模式切换合法性表
 *
 * 合法切换:
 *   IDLE          → CHARGING, OTG, PTM, LEARN, PASSTHROUGH
 *   CHARGING      → IDLE, PEAK_POWER_L1, PEAK_POWER_L2, PASSTHROUGH
 *   OTG           → IDLE
 *   PTM           → IDLE, CHARGING
 *   PEAK_POWER_L1 → IDLE, CHARGING
 *   PEAK_POWER_L2 → IDLE, CHARGING
 *   LEARN         → IDLE
 *   PASSTHROUGH   → IDLE, CHARGING
 *
 * @param from       当前模式
 * @param to         目标模式
 * @return 1 合法切换, 0 非法切换
 */
uint8_t bq25710_mode_transition_allowed(bq25710_operation_mode_t from,
                                        bq25710_operation_mode_t to);

/* ---------- 充电管理 ---------- */

/**
 * @brief 初始化充电上下文并配置电池参数
 * @param chemistry             电池化学类型 @battery_chemistry_t
 * @param cells                 串联节数    @battery_cell_count_t
 * @param precharge_timeout_ms  预充电超时时间ms
 * @param cc_timeout_ms         CC 超时时间ms
 * @param cv_timeout_ms         CV 超时超时时间ms
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM
 */
bq25710_err_t bq25710_charge_init(battery_chemistry_t chemistry, 
                                  battery_cell_count_t cells, 
                                  uint32_t precharge_timeout_ms, 
                                  uint32_t cc_timeout_ms, 
                                  uint32_t cv_timeout_ms);

/**
 * @brief 充电状态机周期调用
 * @details 执行: DETECTION → PRECHARGE → CC → CV → DONE → FAULT 状态转换
 *          同时执行喂狗、超时保护、C/10 终止检测
 * @return BQ25710_ERR_OK / BQ25710_ERR_TIMEOUT / BQ25710_ERR_FAULT
 */
bq25710_err_t bq25710_charge_run(void);

/**
 * @brief 获取当前充电阶段
 * @return 充电阶段枚举值
 */
bq25710_charge_stage_t bq25710_charge_get_stage(void);

/**
 * @brief 获取 BQ25710 可直接使用的电池参数
 * @param chemistry 化学类型
 * @param cells     串联节数
 * @param params_out 输出参数指针
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM / BQ25710_ERR_NULL_PTR
 */
bq25710_err_t bq25710_get_battery_params(battery_chemistry_t chemistry,
                                         battery_cell_count_t cells,
                                         battery_ti_bq25710_params_t *params_out);

/* ---------- OTG 管理 ---------- */

/**
 * @brief 使能 OTG 反向输出
 * @param voltage_mv 输出电压 (mV), 高量程 4280~20800, 低量程 3000~19520
 * @param current_ma 输出电流限制 (mA), 50~6350, 步进 50mA
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM
 */
bq25710_err_t bq25710_otg_enable(uint16_t voltage_mv, uint16_t current_ma);

/**
 * @brief 禁用 OTG 反向输出, 返回 IDLE 模式
 * @return BQ25710_ERR_OK 成功, 其他为错误码
 */
bq25710_err_t bq25710_otg_disable(void);

/* ---------- 输入功率管理 ---------- */

/**
 * @brief 设置 IDPM 输入电流阈值 (IIN_HOST)
 * @param current_ma 输入电流限制 (mA), 50~6350, 步进 50mA
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM
 */
bq25710_err_t bq25710_idpm_set_threshold(uint16_t current_ma);

/**
 * @brief 设置 VDPM 输入电压阈值
 * @param voltage_mv VINDPM 阈值 (mV), 3200~19520, 步进 64mV
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM
 */
bq25710_err_t bq25710_vdpm_set_threshold(uint16_t voltage_mv);

/**
 * @brief 配置 ILIM_HIZ 引脚硬件限流
 * @param enable   1=使能外部 ILIM_HIZ 引脚限流
 * @param ilim2_mv ILIM2 阈值电压 (mV, 通过 ProchotOption0 ILIM2_VTH 设置百分比)
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM
 */
bq25710_err_t bq25710_ilim_hiz_config(uint8_t enable, uint16_t ilim2_mv);

/**
 * @brief 运行 ICO (输入电流优化器) 检测
 * @details 使能 ICO 算法 → 等待 ICO_DONE → 读取优化后的 DPM 电流
 * @param optimized_ma_out 输出参数, ICO 优化后的输入电流 (mA), 可为 NULL
 * @return BQ25710_ERR_OK / BQ25710_ERR_TIMEOUT
 */
bq25710_err_t bq25710_ico_run(uint16_t *optimized_ma_out);

/**
 * @brief 配置两级峰值功率模式
 * @param level     1=Level1(适配器+电池联合), 2=Level2(仅电池补偿)
 * @param ilim1_ma  ILIM1 直流额定值 (mA)
 * @param ilim2_ma  ILIM2 过载值 (mA, 为 ILIM1 的 110%~450%)
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM
 */
bq25710_err_t bq25710_peak_power_config(uint8_t level, uint16_t ilim1_ma,
                                        uint16_t ilim2_ma);

/* ---------- PTM 直通模式 ---------- */

/**
 * @brief 进入 PTM 直通模式
 * @details 适配器功率直接穿透到系统, 绕过 Buck-Boost 开关损耗
 * @param current_limit_ma PTM 下输入电流限制 (mA, 0=使用已有设置)
 * @return BQ25710_ERR_OK / BQ25710_ERR_MODE
 */
bq25710_err_t bq25710_ptm_enter(uint16_t current_limit_ma);

/**
 * @brief 退出 PTM 直通模式
 * @return BQ25710_ERR_OK 成功, 其他为错误码
 */
bq25710_err_t bq25710_ptm_exit(void);

/* ---------- VAP 有源保护 ---------- */

/**
 * @brief 配置 VAP (最小电压有源保护)
 * @param enable         1=使能 VAP 模式
 * @param conservative   1=保守 VAP 模式 (更保守的能量释放)
 * @param vsys_discharge_thresh_100mv VSYS 放电阈值 (0~15, 单位 0.1V, 叠加到 VSYS_TH1 基础上)
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM
 */
bq25710_err_t bq25710_vap_config(uint8_t enable, uint8_t conservative,
                                 uint8_t vsys_discharge_thresh_100mv);

/* ---------- PROCHOT 管理 ---------- */

/**
 * @brief 配置 PROCHOT 引脚基本属性
 * @param polarity    极性 (开漏低有效 / 推挽高有效) — 通过外部电路决定
 * @param pulse_width_us 脉冲宽度枚举
 * @param output_mode 输出模式 (脉冲 / 扩展)
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM
 */
bq25710_err_t bq25710_prochot_config(bq25710_prochot_polarity_t polarity,
                                     bq25710_prochot_width_t pulse_width_us,
                                     bq25710_prochot_output_mode_t output_mode);

/**
 * @brief 设置 PROCHOT 触发源掩码
 * @param trigger_mask 触发源位掩码 (bq25710_prochot_src_t 按位 OR)
 * @return BQ25710_ERR_OK
 */
bq25710_err_t bq25710_prochot_set_trigger_mask(uint16_t trigger_mask);

/**
 * @brief 设置 PROCHOT IDCHG 放电过流阈值
 * @param current_ma 阈值电流 (mA), 0~32256, 步进 512mA, 偏移 +128mA
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM
 */
bq25710_err_t bq25710_prochot_set_idchg_threshold(uint16_t current_ma);

/**
 * @brief PROCHOT 中断服务例程 — 读取并识别触发源
 * @param trigger_source_out 输出参数, 当前触发的源位掩码 (0=无触发)
 * @return BQ25710_ERR_OK
 */
bq25710_err_t bq25710_prochot_isr(uint16_t *trigger_source_out);

/**
 * @brief 获取 PROCHOT 当前触发源 (不修改寄存器)
 * @return 触发源位掩码
 */
uint16_t bq25710_prochot_get_trigger_source(void);

/**
 * @brief 清除所有 PROCHOT 触发状态
 * @return BQ25710_ERR_OK
 */
bq25710_err_t bq25710_prochot_clear_all(void);

/* ---------- PSYS 系统功率监控 ---------- */

/**
 * @brief 配置 PSYS 输出
 * @param enable        1=使能 PSYS 输出缓冲器
 * @param current_ratio 0=0.25uA/W, 1=1uA/W (符合 IMVP8/IMVP9 规范)
 * @return BQ25710_ERR_OK
 */
bq25710_err_t bq25710_psys_config(uint8_t enable, uint8_t current_ratio);

/**
 * @brief 读取 PSYS 系统总功率
 * @param power_mw_out 输出参数, 系统总功率 (mW)
 * @return BQ25710_ERR_OK
 */
bq25710_err_t bq25710_psys_read_power_mw(int32_t *power_mw_out);

/**
 * @brief 设置平台功率预算 (当 PSYS 超预算时自动降低充电电流)
 * @param max_power_mw 最大允许系统功率 (mW), 0=禁用功率预算
 * @return BQ25710_ERR_OK
 */
bq25710_err_t bq25710_psys_set_power_budget(int32_t max_power_mw);

/* ---------- 学习模式 ---------- */

/**
 * @brief 进入学习模式 (电池放电校准)
 * @return BQ25710_ERR_OK / BQ25710_ERR_MODE
 */
bq25710_err_t bq25710_learn_enter(void);

/**
 * @brief 退出学习模式
 * @return BQ25710_ERR_OK
 */
bq25710_err_t bq25710_learn_exit(void);

/**
 * @brief 启动完整充放电学习循环
 * @details CC 充电 → CV 充电 → 放电 → 库仑计数积分 → 计算容量
 *          本函数阻塞直到学习完成或超时 (最长约 6 小时)
 * @return BQ25710_ERR_OK / BQ25710_ERR_TIMEOUT
 */
bq25710_err_t bq25710_learn_start_cycle(void);

/**
 * @brief 获取学习到的电池容量
 * @param capacity_mah_out 输出参数, 容量 (mAh)
 * @return BQ25710_ERR_OK / BQ25710_ERR_STATE (未完成学习)
 */
bq25710_err_t bq25710_learn_get_capacity_mah(float *capacity_mah_out);

/* ---------- ADC 监测 ---------- */

/**
 * @brief 读取全部 8 通道 ADC 数据 (含动态增益补偿)
 * @param data 输出参数, ADC 数据结构体
 * @return BQ25710_ERR_OK / BQ25710_ERR_NULL_PTR
 */
bq25710_err_t bq25710_adc_read_all(bq25710_adc_data_t *data);

/**
 * @brief 读取单个 ADC 通道
 * @param channel 通道选择: 0=VBAT, 1=VSYS, 2=ICHG, 3=IDCHG, 4=IIN, 5=PSYS, 6=VBUS, 7=CMPIN
 * @param value_mv_or_ma 输出参数, 电压(mV)或电流(mA)或功率(mW)
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM
 */
bq25710_err_t bq25710_adc_read_channel(uint8_t channel, int32_t *value_mv_or_ma);

/**
 * @brief 启动 ADC 连续转换模式
 * @param interval_ms 采样间隔 (ms), 硬件固定每秒一次, 此参数为软件轮询间隔
 * @return BQ25710_ERR_OK
 */
bq25710_err_t bq25710_adc_start_continuous(uint16_t interval_ms);

/**
 * @brief 停止 ADC 连续转换, 切换回单次模式
 * @return BQ25710_ERR_OK
 */
bq25710_err_t bq25710_adc_stop_continuous(void);

/* ---------- 故障管理 ---------- */

/**
 * @brief 综合故障检测 — 读取 ChargerStatus + ProchotStatus
 * @param mask 输出参数, 故障掩码结构体
 * @return BQ25710_ERR_OK / BQ25710_ERR_NULL_PTR
 */
bq25710_err_t bq25710_fault_check(bq25710_fault_mask_t *mask);

/**
 * @brief 清除所有故障锁存位
 * @return BQ25710_ERR_OK
 */
bq25710_err_t bq25710_fault_clear_all(void);

/**
 * @brief 获取活动故障的详细描述字符串
 * @param mask  故障掩码
 * @param buf   输出缓冲区
 * @param buf_size 缓冲区大小
 * @return 写入的字符串长度
 */
int bq25710_fault_get_detail(const bq25710_fault_mask_t *mask,
                             char *buf, int buf_size);

/* ---------- 看门狗管理 ---------- */


/**
 * @brief 配置看门狗超时时间
 * @param timeout_sec 超时时间: bq25710_watchdog_t 枚举值
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM
 */
bq25710_err_t bq25710_wdt_config(bq25710_watchdog_t timeout_sec);

/**
 * @brief 喂狗 — 重置看门狗定时器
 * @return BQ25710_ERR_OK
 */
bq25710_err_t bq25710_wdt_kick(void);

/* ---------- 自动检测 ---------- */

/**
 * @brief 自动检测电池节数 (通过 CELL_BATPRESZ 引脚电压)
 * @param cells_out 输出参数, 检测到的节数 (1~4)
 * @return BQ25710_ERR_OK / BQ25710_ERR_BAT_MISSING
 */
bq25710_err_t bq25710_auto_detect_cells(battery_cell_count_t *cells_out);

/**
 * @brief 自动检测电池化学类型 (小电流充电观察电压平台)
 * @param cells     已知的电池节数
 * @param chem_out  输出参数, 检测到的化学类型
 * @return BQ25710_ERR_OK / BQ25710_ERR_BAT_MISSING
 */
bq25710_err_t bq25710_auto_detect_chemistry(battery_cell_count_t cells,
                                            battery_chemistry_t *chem_out);

/* ---------- 系统信息 ---------- */

/**
 * @brief 打印全部 22 个寄存器 (含位字段分解和物理量换算)
 */
void bq25710_dump_all_registers(void);

/**
 * @brief 获取综合系统状态
 * @param status 输出参数, 系统状态结构体
 * @return BQ25710_ERR_OK / BQ25710_ERR_NULL_PTR
 */
bq25710_err_t bq25710_get_system_status(bq25710_system_status_t *status);

/**
 * @brief 打印格式化的 ASCII 状态报告
 */
void bq25710_print_status_report(void);


#endif /* BQ25710_H */
