/**
 * @file    bq25710_full_driver.c
 * @brief   BQ25710 全功能统一驱动程序 — 完整实现
 * @author  Generated by File Agent
 * @version 2.0.0
 * @date    2026-06-11
 *
 * @details
 * 本文件实现 BQ25710 全部 15 个功能模块, 覆盖:
 *   模式管理 / 充电管理 / OTG / 输入功率管理 / PTM / VAP /
 *   PROCHOT / PSYS / 学习模式 / ADC 监测 / 故障管理 /
 *   看门狗 / 自动检测 / 系统信息 / 初始化与反初始化
 *
 *
 * @copyright Copyright (c) 2026
 */

#include "bq25710.h"
#include <string.h>
#include <stdio.h>


#define LOG_LEVEL   LOG_LVL_DEBUG
#define LOG_TAG     "BQ25710"
#include "logger.h"

/* =========================================================================
 * 内部辅助宏
 * ========================================================================= */


#define REG_ACCESS_CHECK() \
    do { \
        if (!g_bq25710_ctx.initialized) return BQ25710_ERR_NOT_INIT; \
        if (!g_bq25710_ctx.smbus_read || !g_bq25710_ctx.smbus_write) \
            return BQ25710_ERR_I2C; \
    } while (0)

#define PARAM_CHECK(cond) \
    do { if (!(cond)) return BQ25710_ERR_PARAM; } while (0)

/**
 * @brief 检查指针是否为 NULL 宏
 * @param ptr 指针变量
 * @return 错误码
 */
#define NULL_CHECK(ptr)                                                        \
  do {                                                                         \
    if (!(ptr))                                                                \
      return BQ25710_ERR_NULL_PTR;                                             \
  } while (0)

/**
 * @brief 判断电池类型宏
 * @param chemistry 化学类型
 * @return 错误码
 */
#define IS_BATTERY_TYPE(chemistry)                                             \
  do {                                                                         \
    if (((chemistry) != BATTERY_CHEM_LIFEPO4) &&                               \
        ((chemistry) != BATTERY_CHEM_NMC) &&                                   \
        ((chemistry) != BATTERY_CHEM_LIPO) &&                                  \
        ((chemistry) != BATTERY_CHEM_LCO) &&                                   \
        ((chemistry) != BATTERY_CHEM_LTO))                                     \
      return BQ25710_ERR_PARAM;                                                \
  } while (0)

/**
 * @brief 判断电池节数宏
 * @param cells 串联节数
 * @return 错误码
 */
#define IS_BATTERY_CELLS(cells)                                                \
  do {                                                                         \
    if (((cells) < BATTERY_CELLS_1S) || ((cells) > BATTERY_CELLS_4S))          \
      return BQ25710_ERR_PARAM;                                                \
  } while (0)


/* SMBus 7-bit 地址: BQ25710 默认 0x09 (左移一位为 0x12) */
#define BQ25710_SMBUS_ADDR  0x09

/**
 * @brief 读取寄存器 (SMBus Read-Word)
 * @param reg   寄存器地址
 * @param value 输出参数
 * @return 0=成功
 */
static int8_t _reg_read(uint8_t reg, uint16_t *value)
{
    return g_bq25710_ctx.smbus_read(reg, value);
}

/**
 * @brief 写入寄存器 (SMBus Write-Word)
 * @param reg   寄存器地址
 * @param value 要写入的值
 * @return 0=成功
 */
static int8_t _reg_write(uint8_t reg, uint16_t value)
{
    return g_bq25710_ctx.smbus_write(reg, value);
}

/**
 * @brief 读-修改-写寄存器
 * @param reg       寄存器地址
 * @param mask      要修改的位掩码
 * @param new_bits  新的位值 (已对齐到 mask 位置)
 * @return 0=成功
 */
static int8_t _reg_rmw(uint8_t reg, uint16_t mask, uint16_t new_bits)
{
    uint16_t val;
    int8_t ret;

    ret = _reg_read(reg, &val);
    if (ret != 0) return BQ25710_ERR_I2C;

    val = (val & ~mask) | (new_bits & mask);

    ret = _reg_write(reg, val);
    if (ret != 0) return BQ25710_ERR_I2C;

    return BQ25710_ERR_OK;
}

/**
 * @brief 通用步进参数校验
 * 
 * @param value   待校验的值
 * @param min_val 最小允许值
 * @param max_val 最大允许值
 * @param step    步进值
 * @return int8_t 状态码
 */
static int8_t validate_step(uint16_t value, uint16_t min_val, uint16_t max_val, uint16_t step)
{
    if ((value < min_val) || 
        (value > max_val) ||
        ((value % step) != 0)) 
    {
        return BQ25710_ERR_PARAM;
    }
    return BQ25710_ERR_OK;
}
/* =========================================================================
 * 全局驱动上下文实例
 * ========================================================================= */
bq25710_drv_ctx_t g_bq25710_ctx = {0};


/**< 英文运行模式名称字符串 */
const char *const bq25710_mode_names_en[] = {
    [BQ25710_MODE_IDLE]          = "IDLE",
    [BQ25710_MODE_CHARGING]      = "CHARGING",
    [BQ25710_MODE_OTG]           = "OTG",
    [BQ25710_MODE_PTM]           = "PTM",
    [BQ25710_MODE_PEAK_POWER_L1] = "PEAK_POWER_L1",
    [BQ25710_MODE_PEAK_POWER_L2] = "PEAK_POWER_L2",
    [BQ25710_MODE_LEARN]         = "LEARN",
    [BQ25710_MODE_PASSTHROUGH]   = "PASSTHROUGH",
};

/**< 英文充电阶段名称字符串 */
static const char *const _chg_stage_names_en[] = {
    [BQ25710_CHG_STAGE_IDLE]       = "IDLE",
    [BQ25710_CHG_STAGE_DETECTION]  = "DETECTION",
    [BQ25710_CHG_STAGE_PRECHARGE]  = "PRECHARGE",
    [BQ25710_CHG_STAGE_CC]         = "CC",
    [BQ25710_CHG_STAGE_CV]         = "CV",
    [BQ25710_CHG_STAGE_DONE]       = "DONE",
    [BQ25710_CHG_STAGE_FAULT]      = "FAULT",
};

/**< 中文运行模式名称字符串 */
const char *const bq25710_mode_names_cn[] = {
    [BQ25710_MODE_IDLE]          = "空闲",
    [BQ25710_MODE_CHARGING]      = "充电",
    [BQ25710_MODE_OTG]           = "OTG",
    [BQ25710_MODE_PTM]           = "直通",
    [BQ25710_MODE_PEAK_POWER_L1] = "峰值功率L1",
    [BQ25710_MODE_PEAK_POWER_L2] = "峰值功率L2",
    [BQ25710_MODE_LEARN]         = "学习",
    [BQ25710_MODE_PASSTHROUGH]   = "NVDC 旁路",
};

/**< 英文充电阶段名称字符串 */
static const char *const _chg_stage_names_cn[] = {
    [BQ25710_CHG_STAGE_IDLE]       = "空闲",
    [BQ25710_CHG_STAGE_DETECTION]  = "检测",
    [BQ25710_CHG_STAGE_PRECHARGE]  = "预充电",
    [BQ25710_CHG_STAGE_CC]         = "恒流快充",
    [BQ25710_CHG_STAGE_CV]         = "恒压充电",
    [BQ25710_CHG_STAGE_DONE]       = "充电完成",
    [BQ25710_CHG_STAGE_FAULT]      = "故障",
};


/* =========================================================================
 * 电池参数查找表 (8 组: 2 化学类型 × 4 节数)
 *
 * 寄存器计算公式 (注释中标明):
 *   MaxChargeVoltage:  reg = (总电压_mV / 8) << 3  [LSB=8mV, 偏移3bit]
 *   MinSystemVoltage:  reg = (电压_mV / 256) << 8  [LSB=256mV, 偏移8bit]
 *   ChargeCurrent:     reg = (电流_mA / 64) << 6   [LSB=64mA, 偏移6bit]
 *
 * LiFePO4: 单节终止 3.60V, 平台 3.2V
 * NMC:     单节终止 4.20V, 平台 3.7V
 * ========================================================================= */


/* =========================================================================
 * 初始化 / 反初始化
 * ========================================================================= */
/**
 * @brief 初始化 BQ25710 全功能驱动
 * @param smbus_read   SMBus 读寄存器回调
 * @param smbus_write  SMBus 写寄存器回调
 * @param delay_ms     毫秒延时回调
 * @return BQ25710_ERR_OK 成功, 其他为错误码
 */
bq25710_err_t bq25710_init(bq25710_smbus_read_cb_t  smbus_read,
                            bq25710_smbus_write_cb_t smbus_write,
                            bq25710_delay_ms_cb_t    delay_ms)
{
    if (!smbus_read || !smbus_write || !delay_ms)
    {
        return BQ25710_ERR_NULL_PTR;
    }

    /* 填充回调 */
    g_bq25710_ctx.smbus_read  = smbus_read;
    g_bq25710_ctx.smbus_write = smbus_write;
    g_bq25710_ctx.delay_ms    = delay_ms;

    /* 验证器件 ID */
    BQ25710_DeviceID_t         DevID;         // [0xFF] 器件识别码
    int8_t ret = _reg_read(BQ25710_REG_DEVICE_ID, &DevID.all);
    if (ret != 0) 
    {
        return BQ25710_ERR_I2C;
    }

    if (DevID.maps.DEVICE_ID != BQ25710_DEVICE_ID_VAL) 
    {
        return BQ25710_ERR_DEVICE_ID;
    }

    /* 验证厂商 ID */
    BQ25710_ManufactureID_t    MfrID;         // [0xFE] 厂商识别码
    ret = _reg_read(BQ25710_REG_MANUFACTURE_ID, &MfrID.all);
    if (ret != 0) 
    {
        return BQ25710_ERR_I2C;
    }

    if (MfrID.maps.MANUFACTURE_ID != BQ25710_MFR_ID_VAL) 
    {
        return BQ25710_ERR_DEVICE_ID;
    }
    

    /* 初始化上下文 */
    g_bq25710_ctx.initialized           = 1;
    g_bq25710_ctx.mode                  = BQ25710_MODE_IDLE;
    g_bq25710_ctx.prev_mode             = BQ25710_MODE_IDLE;
    g_bq25710_ctx.prochot_trigger_mask  = BQ25710_PROCHOT_SRC_NONE;
    g_bq25710_ctx.prochot_extended_mode = 0;
    g_bq25710_ctx.wdt_timeout_ms        = 0;
    g_bq25710_ctx.last_kick_ms          = 0;
    g_bq25710_ctx.learn_capacity_mah    = 0.0f;
    g_bq25710_ctx.learn_complete        = 0;
    g_bq25710_ctx.tick_ms               = 0;
    g_bq25710_ctx.tick_valid            = 0;

    /* 清零充电上下文 */
    memset(&g_bq25710_ctx.charge, 0, sizeof(g_bq25710_ctx.charge));

    return BQ25710_ERR_OK;
}

/**
 * @brief  反初始化驱动, 安全关闭所有功能
 * @return BQ25710_ERR_OK 成功
 */
bq25710_err_t bq25710_deinit(void)
{
    if (!g_bq25710_ctx.initialized)
    {
        return BQ25710_ERR_NOT_INIT;
    }

    /* 安全关闭: 先禁止充电, 再关 OTG, 再关各种模式 */
    BQ25710_ChargeOption0_t opt0;
    _reg_read(BQ25710_REG_CHARGE_OPTION_0, &opt0.all);
    opt0.maps.CHRG_INHIBIT = 1;  /* 禁止充电 */
    _reg_write(BQ25710_REG_CHARGE_OPTION_0, opt0.all);

    BQ25710_ChargeOption3_t opt3;
    _reg_read(BQ25710_REG_CHARGE_OPTION_3, &opt3.all);
    opt3.maps.EN_OTG = 0;  /* 关 OTG */
    _reg_write(BQ25710_REG_CHARGE_OPTION_3, opt3.all);

    /* 清除上下文 */
    memset(&g_bq25710_ctx, 0, sizeof(g_bq25710_ctx));
    return BQ25710_ERR_OK;
}

/* =========================================================================
 * 模式管理
 * ========================================================================= */

/**
 * @brief 模式切换合法性表
 *
 * 合法切换:
 *   IDLE          → CHARGING, OTG, PTM, LEARN, PASSTHROUGH
 *   CHARGING      → IDLE, PEAK_POWER_L1, PEAK_POWER_L2, PASSTHROUGH
 *   OTG           → IDLE
 *   PTM           → IDLE, CHARGING
 *   PEAK_POWER_L1 → IDLE, CHARGING
 *   PEAK_POWER_L2 → IDLE, CHARGING
 *   LEARN         → IDLE
 *   PASSTHROUGH   → IDLE, CHARGING
 *
 * @param from       当前模式
 * @param to         目标模式
 * @return 1 合法切换, 0 非法切换
 */
uint8_t bq25710_mode_transition_allowed(bq25710_operation_mode_t from,
                                         bq25710_operation_mode_t to)
{
    /* 同模式切换视为合法 */
    if (from == to) return 1;

    switch (from) {
    case BQ25710_MODE_IDLE: 
        return (to == BQ25710_MODE_CHARGING ||
                to == BQ25710_MODE_OTG ||
                to == BQ25710_MODE_PTM ||
                to == BQ25710_MODE_LEARN ||
                to == BQ25710_MODE_PASSTHROUGH);
    case BQ25710_MODE_CHARGING:
        return (to == BQ25710_MODE_IDLE ||
                to == BQ25710_MODE_PEAK_POWER_L1 ||
                to == BQ25710_MODE_PEAK_POWER_L2 ||
                to == BQ25710_MODE_PASSTHROUGH);
    case BQ25710_MODE_OTG:
        return (to == BQ25710_MODE_IDLE);
    case BQ25710_MODE_PTM:
        return (to == BQ25710_MODE_IDLE ||
                to == BQ25710_MODE_CHARGING);
    case BQ25710_MODE_PEAK_POWER_L1:
    case BQ25710_MODE_PEAK_POWER_L2:
        return (to == BQ25710_MODE_IDLE ||
                to == BQ25710_MODE_CHARGING);
    case BQ25710_MODE_LEARN:
        return (to == BQ25710_MODE_IDLE);
    case BQ25710_MODE_PASSTHROUGH:
        return (to == BQ25710_MODE_IDLE ||
                to == BQ25710_MODE_CHARGING);
    default:
        return 0;
    }
}

/**
 * @brief 内部: 停止当前模式
 */
static bq25710_err_t _mode_stop_current(void)
{
    BQ25710_ChargeOption0_t opt0;
    BQ25710_ChargeOption1_t opt1;
    BQ25710_ChargeOption3_t opt3;

    _reg_read(BQ25710_REG_CHARGE_OPTION_0, &opt0.all);
    _reg_read(BQ25710_REG_CHARGE_OPTION_1, &opt1.all);
    _reg_read(BQ25710_REG_CHARGE_OPTION_3, &opt3.all);

    switch (g_bq25710_ctx.mode) 
    {
    case BQ25710_MODE_CHARGING:
    case BQ25710_MODE_PEAK_POWER_L1:
    case BQ25710_MODE_PEAK_POWER_L2:
        /* 禁止充电 */
        opt0.maps.CHRG_INHIBIT = 1;
        /* 关峰值功率 */
        if (g_bq25710_ctx.mode == BQ25710_MODE_PEAK_POWER_L1 ||
            g_bq25710_ctx.mode == BQ25710_MODE_PEAK_POWER_L2) 
        {
            BQ25710_ChargeOption2_t opt2;
            _reg_read(BQ25710_REG_CHARGE_OPTION_2, &opt2.all);
            opt2.maps.EN_PKPWR_VSYS = 0;
            opt2.maps.EN_PKPWR_IDPM = 0;
            _reg_write(BQ25710_REG_CHARGE_OPTION_2, opt2.all);
        }
        break;
    case BQ25710_MODE_OTG:
        opt3.maps.EN_OTG = 0;                   /* 关 OTG */
        break;
    case BQ25710_MODE_PTM:
        opt1.maps.EN_PTM = 0;                   /* 关 PTM */
        break;
    case BQ25710_MODE_LEARN:
        opt0.maps.EN_LEARN = 0;                 /* 关 LEARN */
        break;
    default:
        break;
    }

    _reg_write(BQ25710_REG_CHARGE_OPTION_0, opt0.all);
    _reg_write(BQ25710_REG_CHARGE_OPTION_1, opt1.all);
    _reg_write(BQ25710_REG_CHARGE_OPTION_3, opt3.all);

    return BQ25710_ERR_OK;
}

/**
 * @brief 内部: 启动新模式
 */
static bq25710_err_t _mode_start_new(bq25710_operation_mode_t mode)
{
    BQ25710_ChargeOption0_t opt0;
    BQ25710_ChargeOption1_t opt1;
    BQ25710_ChargeOption3_t opt3;

    _reg_read(BQ25710_REG_CHARGE_OPTION_0, &opt0.all);
    _reg_read(BQ25710_REG_CHARGE_OPTION_1, &opt1.all);
    _reg_read(BQ25710_REG_CHARGE_OPTION_3, &opt3.all);

    switch (mode) {
    case BQ25710_MODE_CHARGING:
        opt0.maps.EN_LDO  = 1;                  /* 使能 LDO */
        opt0.maps.EN_IDPM = 1;                  /* 使能 IDPM */
        opt0.maps.CHRG_INHIBIT = 0;             /* 使能充电 */
        break;
    case BQ25710_MODE_OTG:
        opt3.maps.EN_OTG = 1;                   /* 使能 OTG */
        break;
    case BQ25710_MODE_PTM:
        opt1.maps.EN_PTM = 1;                   /* 使能 PTM */
        break;
    case BQ25710_MODE_LEARN:
        opt0.maps.EN_LEARN = 1;                 /* 使能 LEARN */
        break;
    case BQ25710_MODE_PASSTHROUGH:
        /* NVDC 功率路径自动管理: 停止充电让硬件自行管理 */
        opt0.maps.CHRG_INHIBIT = 1;             /* 禁止充电 */
        break;
    case BQ25710_MODE_IDLE:
        opt0.maps.CHRG_INHIBIT = 1;             /* 禁止充电 */
        break;
    default:
        break;
    }

    _reg_write(BQ25710_REG_CHARGE_OPTION_0, opt0.all);
    _reg_write(BQ25710_REG_CHARGE_OPTION_1, opt1.all);
    _reg_write(BQ25710_REG_CHARGE_OPTION_3, opt3.all);

    return BQ25710_ERR_OK;
}

bq25710_err_t bq25710_set_mode(bq25710_operation_mode_t mode)
{
    REG_ACCESS_CHECK();

    if (mode > BQ25710_MODE_PASSTHROUGH)
        return BQ25710_ERR_PARAM;

    if (!bq25710_mode_transition_allowed(g_bq25710_ctx.mode, mode))
        return BQ25710_ERR_MODE;

    /* 同模式无操作 */
    if (g_bq25710_ctx.mode == mode)
        return BQ25710_ERR_OK;

    /* 安全序列: 停止当前 → 延迟 10ms → 启动新 */
    _mode_stop_current();
    g_bq25710_ctx.delay_ms(10);
    _mode_start_new(mode);

    g_bq25710_ctx.prev_mode = g_bq25710_ctx.mode;
    g_bq25710_ctx.mode      = mode;

    /* 进入充电模式时重置充电状态机 */
    if (mode == BQ25710_MODE_CHARGING) 
    {
        g_bq25710_ctx.charge.stage = BQ25710_CHG_STAGE_DETECTION;
    }

    return BQ25710_ERR_OK;
}

/**
 * @brief 获取当前操作模式
 * @return 当前操作模式
 */
bq25710_operation_mode_t bq25710_get_mode(void)
{
    return g_bq25710_ctx.mode;
}

/* =========================================================================
 * 充电管理
 * ========================================================================= */

/**
 * @brief 初始化充电上下文并配置电池参数
 * @param chemistry             电池化学类型 @battery_chemistry_t
 * @param cells                 串联节数    @battery_cell_count_t
 * @param precharge_timeout_ms  预充电超时时间ms
 * @param cc_timeout_ms         CC 超时时间ms
 * @param cv_timeout_ms         CV 超时超时时间ms
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM
 */
bq25710_err_t bq25710_charge_init(battery_chemistry_t chemistry, 
                                  battery_cell_count_t cells, 
                                  uint32_t precharge_timeout_ms, 
                                  uint32_t cc_timeout_ms, 
                                  uint32_t cv_timeout_ms)
{
    REG_ACCESS_CHECK();
    IS_BATTERY_TYPE(chemistry);
    IS_BATTERY_CELLS(cells);

    int8_t result;
    battery_ret_t battery_ret;
    uint16_t reg_value;

    battery_ret = battery_ti_get_bq25710_params(chemistry, cells,
                                                &g_bq25710_ctx.charge.params);
    if (battery_ret != BATTERY_RET_OK) {
        return BQ25710_ERR_PARAM;
    }
    
    /* 填充充电上下文 */
    g_bq25710_ctx.charge.chemistry             = chemistry;                                                                         /** 电池化学类型 */
    g_bq25710_ctx.charge.cells                 = cells;                                                                             /** 串联节数 */
    g_bq25710_ctx.charge.stage                 = BQ25710_CHG_STAGE_DETECTION;                                                       /** 充电阶段 */
    g_bq25710_ctx.charge.stage_start_ms        = g_bq25710_ctx.tick_ms;                                                             /** 充电阶段开始时间 */
    g_bq25710_ctx.charge.total_elapsed_ms      = 0;                                                                                 /** 充电总时间 */
    g_bq25710_ctx.charge.precharge_timeout_ms  = (precharge_timeout_ms)?precharge_timeout_ms:BQ25710_PRECHARGE_TIMEOUT_MS_DEFAULT;  /* 预充电超时时间 */
    g_bq25710_ctx.charge.cc_timeout_ms         = (cc_timeout_ms)?cc_timeout_ms:BQ25710_CC_TIMEOUT_MS_DEFAULT;                       /* CC 超时时间ms */
    g_bq25710_ctx.charge.cv_timeout_ms         = (cv_timeout_ms)?cv_timeout_ms:BQ25710_CV_TIMEOUT_MS_DEFAULT;                       /* CV 超时时间ms */
    g_bq25710_ctx.charge.wdt_kick_interval_ms  = 80 * 1000;                                                                         /* 看门狗喂狗间隔ms */
    g_bq25710_ctx.charge.last_wdt_kick_ms      = 0;                                                                                 /** 上次喂狗时间 */
    g_bq25710_ctx.charge.initialized           = 1;                                                                                 /** 初始化标志 */
    
    /* 校验最大充电电压 VREG */
    result = validate_step(g_bq25710_ctx.charge.params.chg_voltage_mv, 
                           BQ25710_CHG_VOLT_MIN, 
                           BQ25710_CHG_VOLT_MAX, 
                           BQ25710_CHG_VOLT_STEP);
    if (result != BQ25710_ERR_OK)
    {
        LOG_E("无效的最大充电电压: %u mV (范围: %u-%u, 步进: %u)",
              g_bq25710_ctx.charge.params.chg_voltage_mv, 
              BQ25710_CHG_VOLT_MIN, 
              BQ25710_CHG_VOLT_MAX, 
              BQ25710_CHG_VOLT_STEP);
        return BQ25710_ERR_PARAM;
    }

    /* 校验最小系统电压 MINSYS */
    result = validate_step(g_bq25710_ctx.charge.params.min_sys_voltage_mv, 
                           BQ25710_MINSYS_MIN,
                           BQ25710_MINSYS_MAX, 
                           BQ25710_MINSYS_STEP);
    if (result != BQ25710_ERR_OK) 
    {
        LOG_E("无效的最小系统电压: %u mV (范围: %u-%u, 步进: %u)",
              g_bq25710_ctx.charge.params.min_sys_voltage_mv, 
              BQ25710_MINSYS_MIN, 
              BQ25710_MINSYS_MAX, 
              BQ25710_MINSYS_STEP);
        return result;
    }

    /* 校验充电电流 */
    result = validate_step(g_bq25710_ctx.charge.params.charge_current_ma, 
                           BQ25710_CHG_CURR_MIN, 
                           BQ25710_CHG_CURR_MAX, 
                           BQ25710_CHG_CURR_STEP);
    if (result != BQ25710_ERR_OK) 
    {
        LOG_E("无效的充电电流: %u mA (范围: %u-%u, 步进: %u)",
              g_bq25710_ctx.charge.params.charge_current_ma, 
              BQ25710_CHG_CURR_MIN, 
              BQ25710_CHG_CURR_MAX, 
              BQ25710_CHG_CURR_STEP);
        return result;
    }

    /* 配置充电电压 VREG
     *   reg = (mV / 8) << 3, MaxChargeVoltage [14:3]
     *   例: NMC 4S 16.8V → (16800/8) << 3 = 2100 << 3 = 0x41A0 (实际格式)
     */
    reg_value = (g_bq25710_ctx.charge.params.chg_voltage_mv / 8U) << 3;
    _reg_write(BQ25710_REG_MAX_CHARGE_VOLT, reg_value);

    /* 配置最小系统电压 MINSYS
     *   reg = (mV / 256) << 8, MinSystemVoltage [13:8]
     *   例: NMC 4S 14.336V → (14336/256) << 8 = 56 << 8 = 0x3800
     */
    reg_value = (g_bq25710_ctx.charge.params.min_sys_voltage_mv / BQ25710_MINSYS_STEP) << 8;
    _reg_write(BQ25710_REG_MIN_SYS_VOLTAGE, reg_value);

    /* 配置充电电流
     *   reg = (mA / 64) << 6, ChargeCurrent [12:6]
     *   例: 2000mA → (2000/64) << 6 = 31 << 6 = 0x07C0
     */
    reg_value = (g_bq25710_ctx.charge.params.charge_current_ma / BQ25710_CHG_CURR_STEP) << 6;
    _reg_write(BQ25710_REG_CHARGE_CURRENT, reg_value);

    /* 配置看门狗 */
    BQ25710_ChargeOption0_t opt0;
    _reg_read(BQ25710_REG_CHARGE_OPTION_0, &opt0.all);
    opt0.maps.WDTMR_ADJ = 2;
    _reg_write(BQ25710_REG_CHARGE_OPTION_0, opt0.all);

    /* 以禁止充电开始, 由状态机控制使能 */
    /* 使能 ADC 全通道 */
    BQ25710_ADCOption_t adc;
    _reg_read(BQ25710_REG_ADC_OPTION, &adc.all);
    adc.maps.EN_ADC_VBAT  = 1;  /** 使能 VBAT 通道 */
    adc.maps.EN_ADC_VSYS  = 1;  /** 使能 SYS 通道 */
    adc.maps.EN_ADC_ICHG  = 1;  /** 使能 ICHG 通道 */
    adc.maps.EN_ADC_IDCHG = 1;  /** 使能 IDCHG 通道 */
    adc.maps.EN_ADC_IIN   = 1;  /** 使能 IIN 通道 */
    adc.maps.EN_ADC_VBUS  = 1;  /** 使能 VBUS 通道 */
    adc.maps.ADC_START    = 1;  /** 启动 ADC 转换 */
    adc.maps.ADC_CONV     = 1;  /** 连续模式 */
    _reg_write(BQ25710_REG_ADC_OPTION, adc.all);

    return BQ25710_ERR_OK;
}


/**
 * @brief 充电状态机周期调用
 * @details 执行: DETECTION → PRECHARGE → CC → CV → DONE → FAULT 状态转换
 *          同时执行喂狗、超时保护、C/10 终止检测
 * @return BQ25710_ERR_OK / BQ25710_ERR_TIMEOUT / BQ25710_ERR_FAULT
 */
bq25710_err_t bq25710_charge_run(void)
{
    REG_ACCESS_CHECK();

    if (!g_bq25710_ctx.charge.initialized)
    {
        return BQ25710_ERR_NOT_INIT;
    }

    if (g_bq25710_ctx.mode != BQ25710_MODE_CHARGING)
    {
        return BQ25710_ERR_MODE;
    }

    bq25710_charge_ctx_t *ctx = &g_bq25710_ctx.charge;
    uint32_t now_ms = g_bq25710_ctx.tick_ms;
    uint32_t elapsed_in_stage = now_ms - ctx->stage_start_ms;

    /* 喂狗 */
    if (now_ms - ctx->last_wdt_kick_ms >= ctx->wdt_kick_interval_ms) 
    {
        bq25710_wdt_kick();
        ctx->last_wdt_kick_ms = now_ms;
    }

    /* 读取实时 ADC */
    bq25710_adc_data_t adc;
    bq25710_adc_read_all(&adc);

    /* 读取充电器状态 */
    
    BQ25710_ChargerStatus_t    Status;                      /**< [0x20] 反馈 AC、ICO、故障锁存信息 */
    _reg_read(BQ25710_REG_CHARGER_STATUS, &Status.all);

    /* 检查故障 */
    if (Status.low_byte != 0) 
    {
        ctx->stage = BQ25710_CHG_STAGE_FAULT;
        return BQ25710_ERR_FAULT;
    }

    /* --- 状态机 --- */
    switch (ctx->stage) 
    {
    case BQ25710_CHG_STAGE_DETECTION:                       /**< 检测 — 检测适配器/电池/通信 */
        if (!Status.maps.AC_STAT) return BQ25710_ERR_ADAPTER_MISS;
        if (adc.vbat_mv < 2000) return BQ25710_ERR_BAT_MISSING;

        /* 判断电池当前电压, 决定进入哪个阶段 */
        if (adc.vbat_mv < ctx->params.precharge_thresh_mv) 
        {
            ctx->stage = BQ25710_CHG_STAGE_PRECHARGE;       /**电池亏电, 进入预充电阶段 */
        } 
        else 
        {
            ctx->stage = BQ25710_CHG_STAGE_CC;              /**电池电压正常, 进入 CC 阶段 */
        }
        /* 使能充电 */
        {
            BQ25710_ChargeOption0_t opt0;
            _reg_read(BQ25710_REG_CHARGE_OPTION_0, &opt0.all);
            opt0.maps.CHRG_INHIBIT = 0;
            _reg_write(BQ25710_REG_CHARGE_OPTION_0, opt0.all);
        }
        ctx->stage_start_ms = now_ms;
        break;

    case BQ25710_CHG_STAGE_PRECHARGE:                       /**< 预充电 — LDO 模式, 电池亏电 */
        /* 预充电超时保护 */
        if (elapsed_in_stage > ctx->precharge_timeout_ms) 
        {
            ctx->stage = BQ25710_CHG_STAGE_FAULT;           /** 预充电超时, 进入故障阶段 */
            return BQ25710_ERR_TIMEOUT;
        }
        /* LDO 预充电: 硬件自动管理, 电流钳位 ~384mA (1S) 或更大 */
        /* 当电池电压 ≥ 预充电阈值时, 进入 CC */
        if (adc.vbat_mv >= ctx->params.precharge_thresh_mv) 
        {
            ctx->stage = BQ25710_CHG_STAGE_CC;
            ctx->stage_start_ms = now_ms;
        }
        break;

    case BQ25710_CHG_STAGE_CC:                              /**< 恒流快充 — 最大充电电流 */     
    {
        /* CC 超时保护 */
        if (elapsed_in_stage > ctx->cc_timeout_ms) 
        {
            ctx->stage = BQ25710_CHG_STAGE_FAULT;           /** CC 超时, 进入故障阶段 */
            return BQ25710_ERR_TIMEOUT;
        }
        /* 当 VBAT 接近终止电压 (98%) 时, 自动转入 CV
            * 硬件自动切换 CC→CV, 软件监控 IN_FCHRG → 0 作为进入 CV 标志
            */
        if (adc.vbat_mv >= ctx->params.chg_voltage_mv * 98 / 100) 
        {
            ctx->stage = BQ25710_CHG_STAGE_CV;              /** 进入 CV 阶段 */
            ctx->stage_start_ms = now_ms;
        }
    }
    break;

    case BQ25710_CHG_STAGE_CV:                              /**< 恒压充电 — 电流逐渐下降 */
    {
        /* CV 超时保护 */
        if (elapsed_in_stage > ctx->cv_timeout_ms) 
        {
            ctx->stage = BQ25710_CHG_STAGE_FAULT;           /** CV 超时, 进入故障阶段 */
            return BQ25710_ERR_TIMEOUT;
        }
        /* C/10 终止: ICHG ≤ 充电电流的 10% */
        if (adc.ichg_ma > 0 && adc.ichg_ma <= ctx->params.term_current_ma) 
        {
            ctx->stage = BQ25710_CHG_STAGE_DONE;            /** C/10 终止, 进入完成阶段 */
            ctx->stage_start_ms = now_ms;
        }
    }
    break;

    case BQ25710_CHG_STAGE_DONE:                            /**< 充电完成 — C/10 终止 */
    {
        BQ25710_ChargeOption0_t opt0;
        _reg_read(BQ25710_REG_CHARGE_OPTION_0, &opt0.all);
        opt0.maps.CHRG_INHIBIT = 1;
        _reg_write(BQ25710_REG_CHARGE_OPTION_0, opt0.all);
    }
    break;

    case BQ25710_CHG_STAGE_FAULT:                           /**< 故障 — 检测到故障, 等待恢复 */
    {
        bq25710_fault_clear_all();
        g_bq25710_ctx.delay_ms(100);
    
        BQ25710_ChargerStatus_t    Status;        /**< [0x20] 反馈 AC、ICO、故障锁存信息 */
        _reg_read(BQ25710_REG_CHARGER_STATUS, &Status.all);
        if (Status.low_byte == 0) 
        {
            ctx->stage = BQ25710_CHG_STAGE_DETECTION;
            ctx->stage_start_ms = now_ms;
        }
    }
        break;

    default:
        break;
    }

    ctx->total_elapsed_ms = now_ms - ctx->stage_start_ms + elapsed_in_stage;
    return BQ25710_ERR_OK;
}

/**
 * @brief 获取当前充电阶段
 * @return 充电阶段枚举值
 */
bq25710_charge_stage_t bq25710_charge_get_stage(void)
{
    return g_bq25710_ctx.charge.stage;
}

 /**
 * @brief 获取 BQ25710 可直接使用的电池参数
 * @param chemistry 化学类型
 * @param cells     串联节数
 * @param params_out 输出参数指针
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM / BQ25710_ERR_NULL_PTR
 */
bq25710_err_t bq25710_get_battery_params(battery_chemistry_t chemistry,
                                         battery_cell_count_t cells,
                                         battery_ti_bq25710_params_t *params_out)
{
    battery_ret_t battery_ret;

    NULL_CHECK(params_out);
    IS_BATTERY_TYPE(chemistry);
    IS_BATTERY_CELLS(cells);

    battery_ret = battery_ti_get_bq25710_params(chemistry, cells, params_out);
    if (battery_ret != BATTERY_RET_OK) {
        return BQ25710_ERR_PARAM;
    }

    return BQ25710_ERR_OK;
}

/* =========================================================================
 * 15.4 OTG 管理
 * ========================================================================= */

bq25710_err_t bq25710_otg_enable(uint16_t voltage_mv, uint16_t current_ma)
{
    REG_ACCESS_CHECK();

    /* 范围校验: 低量程 3000~19520, 高量程 4280~20800 */
    uint8_t use_low_range = 0;
    if (voltage_mv >= 3000 && voltage_mv <= 19520) {
        use_low_range = 1;
    } else if (voltage_mv >= 4280 && voltage_mv <= 20800) {
        use_low_range = 0;
    } else {
        return BQ25710_ERR_PARAM;
    }
    if ((current_ma < BQ25710_OTG_CURR_MIN) || (current_ma > BQ25710_OTG_CURR_MAX)) 
    {
        return BQ25710_ERR_PARAM;
    }

    /* 切换到 OTG 模式 (安全序列自动停止当前模式) */
    bq25710_err_t ret = bq25710_set_mode(BQ25710_MODE_OTG);
    if (ret != BQ25710_ERR_OK && ret != BQ25710_ERR_MODE)
        return ret;

    /* 配置 OTG 电压
     *   高量程: offset=1280mV, reg = ((mV - 1280) / 8) << 2  [OTGVoltage 13:2]
     *   低量程: offset=0mV,    reg = (mV / 8) << 2
     *   例: 5V 低量程 → (5000/8) << 2 = 625 << 2 = 0x09C4
     */
    uint16_t offset_mv = use_low_range ? 0 : 1280;
    uint16_t otgv_reg = (uint16_t)((((uint32_t)voltage_mv - offset_mv) / 8) << 2);
    _reg_write(BQ25710_REG_OTG_VOLTAGE, otgv_reg);

    /* 设置量程 */
    BQ25710_ChargeOption3_t opt3;
    _reg_read(BQ25710_REG_CHARGE_OPTION_3, &opt3.all);
    opt3.maps.OTG_RANGE_LOW = use_low_range ? 1 : 0;
    _reg_write(BQ25710_REG_CHARGE_OPTION_3, opt3.all);

    /* 配置 OTG 电流
     *   reg = (mA / 50) << 8, OTGCurrent [14:8]
     *   例: 3000mA → (3000/50) << 8 = 60 << 8 = 0x3C00
     */
    uint16_t otgc_reg = (uint16_t)(((uint32_t)current_ma / 50) << 8);
    _reg_write(BQ25710_REG_OTG_CURRENT, otgc_reg);

    /* 使能 OTG */
    _reg_read(BQ25710_REG_CHARGE_OPTION_3, &opt3.all);
    opt3.maps.EN_OTG = 1;
    _reg_write(BQ25710_REG_CHARGE_OPTION_3, opt3.all);

    return BQ25710_ERR_OK;
}

bq25710_err_t bq25710_otg_disable(void)
{
    REG_ACCESS_CHECK();

    BQ25710_ChargeOption3_t opt3;
    _reg_read(BQ25710_REG_CHARGE_OPTION_3, &opt3.all);
    opt3.maps.EN_OTG = 0;
    _reg_write(BQ25710_REG_CHARGE_OPTION_3, opt3.all);

    g_bq25710_ctx.mode = BQ25710_MODE_IDLE;
    return BQ25710_ERR_OK;
}

/* =========================================================================
 * 15.5 输入功率管理
 * ========================================================================= */

bq25710_err_t bq25710_idpm_set_threshold(uint16_t current_ma)
{
    REG_ACCESS_CHECK();
    
    PARAM_CHECK(current_ma >= 50 && current_ma <= 6400);

    /* IIN_HOST: reg = (mA / 50) << 8, [14:8]
     *   例: 3000mA → (3000/50) << 8 = 60 << 8 = 0x3C00
     */
    uint16_t reg_val = (uint16_t)(((uint32_t)current_ma / 50) << 8);
    return _reg_write(BQ25710_REG_IN_CURR_HOST, reg_val);
}

bq25710_err_t bq25710_vdpm_set_threshold(uint16_t voltage_mv)
{
    REG_ACCESS_CHECK();
    PARAM_CHECK(voltage_mv >= BQ25710_VINDPM_MIN &&
                voltage_mv <= BQ25710_VINDPM_MAX);

    /* VINDPM: reg = (mV / 64) << 6, [13:6]
     *   例: 4200mV → (4200/64) << 6 = 65 << 6 = 0x1040
     */
    uint16_t reg_val = (uint16_t)(((uint32_t)voltage_mv / 64) << 6);
    return _reg_write(BQ25710_REG_INPUT_VOLTAGE, reg_val);
}

bq25710_err_t bq25710_ilim_hiz_config(uint8_t enable, uint16_t ilim2_mv)
{
    REG_ACCESS_CHECK();

    /* EN_EXTILIM: ChargeOption2[7] — 0=仅寄存器, 1=引脚与寄存器取较小值 */
    uint16_t mask = (1 << 7);
    uint16_t bits = enable ? mask : 0;
    return _reg_rmw(BQ25710_REG_CHARGE_OPTION_2, mask, bits);
}

bq25710_err_t bq25710_ico_run(uint16_t *optimized_ma_out)
{
    REG_ACCESS_CHECK();

    /* 使能 ICO 算法 (ChargeOption3[11]) */
    BQ25710_ChargeOption3_t opt3;
    _reg_read(BQ25710_REG_CHARGE_OPTION_3, &opt3.all);
    opt3.maps.EN_ICO_MODE = 1;
    _reg_write(BQ25710_REG_CHARGE_OPTION_3, opt3.all);

    /* 等待 ICO_DONE (ChargerStatus[14]), 最多 10 秒 */
    int timeout = 100;
    while (timeout-- > 0) {
        g_bq25710_ctx.delay_ms(100);
        uint16_t status;
        _reg_read(BQ25710_REG_CHARGER_STATUS, &status);
        if (status & (1 << 14)) break;
    }

    if (timeout <= 0) {
        /* 超时, 关闭 ICO */
        _reg_read(BQ25710_REG_CHARGE_OPTION_3, &opt3.all);
        opt3.maps.EN_ICO_MODE = 0;
        _reg_write(BQ25710_REG_CHARGE_OPTION_3, opt3.all);
        return BQ25710_ERR_TIMEOUT;
    }

    /* 读取优化后的 DPM 电流
     *   InCurrDPM: reg = (mA / 50) << 8, [14:8] 只读
     */
    uint16_t dpm_reg;
    _reg_read(BQ25710_REG_IN_CURR_DPM, &dpm_reg);
    uint16_t dpm_ma = (uint16_t)(((uint32_t)(dpm_reg >> 8) & 0x7F) * 50);

    if (optimized_ma_out) *optimized_ma_out = dpm_ma;

    /* 关闭 ICO */
    _reg_read(BQ25710_REG_CHARGE_OPTION_3, &opt3.all);
    opt3.maps.EN_ICO_MODE = 0;
    _reg_write(BQ25710_REG_CHARGE_OPTION_3, opt3.all);

    return BQ25710_ERR_OK;
}

bq25710_err_t bq25710_peak_power_config(uint8_t level, uint16_t ilim1_ma,
                                         uint16_t ilim2_ma)
{
    REG_ACCESS_CHECK();
    PARAM_CHECK(level == 1 || level == 2);
    PARAM_CHECK(ilim1_ma >= 50 && ilim1_ma <= 6400);
    PARAM_CHECK(ilim2_ma >= ilim1_ma && ilim2_ma <= 28800);

    /* 设置 ILIM1: IIN_HOST 寄存器 */
    bq25710_idpm_set_threshold(ilim1_ma);

    /* 设置 ILIM2 百分比: ILIM2_VTH 5-bit
     *   范围 110%~450%, ILIM2_VTH = 1~25 (对应 110%~450%)
     *   实际上: code 1~25 映射到百分比 110%~230% (step 10%),
     *          code 26~30 映射到 250%~450% (step 50%)
     */
    uint32_t ratio = ((uint32_t)ilim2_ma * 100) / ilim1_ma;  /* 百分比, 如 150 */
    uint8_t ilim2_code;
    if (ratio <= 230) {
        ilim2_code = (uint8_t)((ratio - 110) / 10 + 1);
    } else {
        ilim2_code = (uint8_t)((ratio - 250) / 50 + 26);
    }
    if (ilim2_code < 1)  ilim2_code = 1;
    if (ilim2_code > 30) ilim2_code = 30;

    BQ25710_ProchotOption0_t p0;
    _reg_read(BQ25710_REG_PROCHOT_OPTION_0, &p0.all);
    p0.maps.ILIM2_VTH = ilim2_code;
    _reg_write(BQ25710_REG_PROCHOT_OPTION_0, p0.all);

    /* 使能峰值功率: ChargeOption2 EN_PKPWR_VSYS/IDPM, PKPWR_TOVLD_DEG, PKPWR_TMAX */
    BQ25710_ChargeOption2_t opt2;
    _reg_read(BQ25710_REG_CHARGE_OPTION_2, &opt2.all);

    if (level == 1) {
        /* Level1: 适配器+电池联合, VSYS 下冲 + IDPM 过冲都触发 */
        opt2.maps.EN_PKPWR_VSYS = 1;
        opt2.maps.EN_PKPWR_IDPM = 1;
    } else {
        /* Level2: 仅电池补偿, 只 VSYS 下冲触发 */
        opt2.maps.EN_PKPWR_VSYS = 1;
        opt2.maps.EN_PKPWR_IDPM = 0;
    }
    /* 默认: 过载检测 10ms, 最大过载 20ms */
    opt2.maps.PKPWR_TOVLD_DEG = 2;  /* 10ms */
    opt2.maps.PKPWR_TMAX      = 2;  /* 20ms */
    _reg_write(BQ25710_REG_CHARGE_OPTION_2, opt2.all);

    /* 切换到峰值功率模式 */
    bq25710_operation_mode_t target_mode = (level == 1)
        ? BQ25710_MODE_PEAK_POWER_L1
        : BQ25710_MODE_PEAK_POWER_L2;

    return bq25710_set_mode(target_mode);
}

/* =========================================================================
 * 15.6 PTM 直通模式
 * ========================================================================= */

bq25710_err_t bq25710_ptm_enter(uint16_t current_limit_ma)
{
    REG_ACCESS_CHECK();

    /* 必须先切换到 PTM 模式 */
    bq25710_err_t ret = bq25710_set_mode(BQ25710_MODE_PTM);
    if (ret != BQ25710_ERR_OK) return ret;

    /* 如果指定了电流限制, 设置 IDPM */
    if (current_limit_ma > 0) {
        bq25710_idpm_set_threshold(current_limit_ma);
    }

    return BQ25710_ERR_OK;
}

bq25710_err_t bq25710_ptm_exit(void)
{
    REG_ACCESS_CHECK();
    return bq25710_set_mode(BQ25710_MODE_IDLE);
}

/* =========================================================================
 * 15.7 VAP 有源保护
 * ========================================================================= */

bq25710_err_t bq25710_vap_config(uint8_t enable, uint8_t conservative,
                                  uint8_t vsys_discharge_thresh_100mv)
{
    REG_ACCESS_CHECK();
    PARAM_CHECK(vsys_discharge_thresh_100mv <= 15);

    BQ25710_ChargeOption3_t opt3;
    _reg_read(BQ25710_REG_CHARGE_OPTION_3, &opt3.all);

    if (enable) {
        /* OTG_VAP_MODE=0: 引脚控制 VAP 模式 (非 OTG 模式) */
        opt3.maps.OTG_VAP_MODE = 0;
        opt3.maps.EN_CON_VAP   = conservative ? 1 : 0;
    } else {
        opt3.maps.OTG_VAP_MODE = 1;  /* 恢复为 OTG 控制 */
        opt3.maps.EN_CON_VAP   = 0;
    }
    _reg_write(BQ25710_REG_CHARGE_OPTION_3, opt3.all);

    /* 设置 VSYS 放电阈值: ProchotOption0 VSYS_TH1 [7:4] */
    BQ25710_ProchotOption0_t p0;
    _reg_read(BQ25710_REG_PROCHOT_OPTION_0, &p0.all);
    p0.maps.VSYS_TH1 = vsys_discharge_thresh_100mv;
    _reg_write(BQ25710_REG_PROCHOT_OPTION_0, p0.all);

    return BQ25710_ERR_OK;
}

/* =========================================================================
 * 15.8 PROCHOT 管理
 * ========================================================================= */

bq25710_err_t bq25710_prochot_config(bq25710_prochot_polarity_t polarity,
                                      bq25710_prochot_width_t pulse_width_us,
                                      bq25710_prochot_output_mode_t output_mode)
{
    REG_ACCESS_CHECK();
    PARAM_CHECK(pulse_width_us <= BQ25710_PROCHOT_WIDTH_5MS);

    BQ25710_ProchotStatus_t ps;
    _reg_read(BQ25710_REG_PROCHOT_STATUS, &ps.all);

    /* PROCHOT_WIDTH [13:12] */
    ps.maps.PROCHOT_WIDTH = (uint16_t)pulse_width_us;

    /* EN_PROCHOT_EXIT [14]: 0=脉冲, 1=扩展(保持低直到清除) */
    ps.maps.EN_PROCHOT_EXIT = (output_mode == BQ25710_PROCHOT_MODE_EXTENDED) ? 1 : 0;

    /* PROCHOT_CLEAR [11]: 1=空闲/释放 */
    ps.maps.PROCHOT_CLEAR = 1;

    _reg_write(BQ25710_REG_PROCHOT_STATUS, ps.all);

    g_bq25710_ctx.prochot_extended_mode =
        (output_mode == BQ25710_PROCHOT_MODE_EXTENDED) ? 1 : 0;

    return BQ25710_ERR_OK;
}

bq25710_err_t bq25710_prochot_set_trigger_mask(uint16_t trigger_mask)
{
    REG_ACCESS_CHECK();

    /* ProchotOption1 低字节 [7:0] 对应 8 个触发源使能 */
    BQ25710_ProchotOption1_t p1;
    _reg_read(BQ25710_REG_PROCHOT_OPTION_1, &p1.all);

    uint8_t mask_low = (uint8_t)(trigger_mask & 0xFF);
    p1.maps.PP_ACOK    = (mask_low >> 0) & 1;
    p1.maps.PP_BATPRES = (mask_low >> 1) & 1;
    p1.maps.PP_VSYS    = (mask_low >> 2) & 1;
    p1.maps.PP_IDCHG   = (mask_low >> 3) & 1;
    p1.maps.PP_INOM    = (mask_low >> 4) & 1;
    p1.maps.PP_ICRIT   = (mask_low >> 5) & 1;
    p1.maps.PP_COMP    = (mask_low >> 6) & 1;
    p1.maps.PP_VDPM    = (mask_low >> 7) & 1;

    _reg_write(BQ25710_REG_PROCHOT_OPTION_1, p1.all);
    g_bq25710_ctx.prochot_trigger_mask = trigger_mask;

    return BQ25710_ERR_OK;
}

bq25710_err_t bq25710_prochot_set_idchg_threshold(uint16_t current_ma)
{
    REG_ACCESS_CHECK();
    /* IDCHG_VTH 6-bit: code = (mA - 128) / 512, 范围 0~63
     *   code=0 → 128mA, code=63 → 32256mA
     *   例: 3000mA → (3000-128)/512 = 5 → code=5
     */
    uint16_t code = (current_ma >= 128) ? ((current_ma - 128) / 512) : 0;
    PARAM_CHECK(code <= 63);

    BQ25710_ProchotOption1_t p1;
    _reg_read(BQ25710_REG_PROCHOT_OPTION_1, &p1.all);
    p1.maps.IDCHG_VTH = code;
    _reg_write(BQ25710_REG_PROCHOT_OPTION_1, p1.all);

    return BQ25710_ERR_OK;
}

bq25710_err_t bq25710_prochot_isr(uint16_t *trigger_source_out)
{
    REG_ACCESS_CHECK();
    NULL_CHECK(trigger_source_out);

    /* 读取 ProchotStatus 低字节 (触发源状态) */
    uint16_t ps;
    _reg_read(BQ25710_REG_PROCHOT_STATUS, &ps);

    /* 低字节 [7:0] + bit [8] (EXIT_VAP) + bit [9] (VAP_FAIL) */
    uint16_t sources = (uint16_t)(ps & 0x03FF);
    *trigger_source_out = sources;

    if (sources != 0) {
        /* 扩展模式下需要手动清除 PROCHOT_CLEAR */
        if (g_bq25710_ctx.prochot_extended_mode) {
            BQ25710_ProchotStatus_t ps_reg;
            ps_reg.all = ps;
            ps_reg.maps.PROCHOT_CLEAR = 1;
            _reg_write(BQ25710_REG_PROCHOT_STATUS, ps_reg.all);
        }
    }

    return BQ25710_ERR_OK;
}

uint16_t bq25710_prochot_get_trigger_source(void)
{
    uint16_t ps;
    if (_reg_read(BQ25710_REG_PROCHOT_STATUS, &ps) != 0)
        return 0;
    return (uint16_t)(ps & 0x03FF);
}

bq25710_err_t bq25710_prochot_clear_all(void)
{
    REG_ACCESS_CHECK();

    /* 写 0 到 ProchotStatus 低 10 bits (触发源) + PROCHOT_CLEAR 清零 */
    BQ25710_ProchotStatus_t ps;
    _reg_read(BQ25710_REG_PROCHOT_STATUS, &ps.all);

    /* 保留高 6 bits, 清零低 10 bits */
    ps.all &= 0xFC00;
    ps.maps.PROCHOT_CLEAR = 1;  /* 释放 PROCHOT 引脚 */

    return _reg_write(BQ25710_REG_PROCHOT_STATUS, ps.all);
}

/* =========================================================================
 * 15.9 PSYS 系统功率监控
 * ========================================================================= */

bq25710_err_t bq25710_psys_config(uint8_t enable, uint8_t current_ratio)
{
    REG_ACCESS_CHECK();

    BQ25710_ChargeOption1_t opt1;
    _reg_read(BQ25710_REG_CHARGE_OPTION_1, &opt1.all);
    opt1.maps.EN_PSYS    = enable ? 1 : 0;
    opt1.maps.PSYS_RATIO = current_ratio ? 1 : 0;
    _reg_write(BQ25710_REG_CHARGE_OPTION_1, opt1.all);

    /* 使能 PSYS ADC 通道 */
    if (enable) {
        BQ25710_ADCOption_t adc;
        _reg_read(BQ25710_REG_ADC_OPTION, &adc.all);
        adc.maps.EN_ADC_PSYS = 1;
        _reg_write(BQ25710_REG_ADC_OPTION, adc.all);
    }

    return BQ25710_ERR_OK;
}

bq25710_err_t bq25710_psys_read_power_mw(int32_t *power_mw_out)
{
    REG_ACCESS_CHECK();
    NULL_CHECK(power_mw_out);

    /* 读取 ADC_PSYS: ADCVBUSPSYS [7:0], LSB=12mV (电压输出)
     * PSYS 电压输出 → 电流 (uA) = 电压 / 检测电阻
     * 功率 (W) = 电流 (uA) / PSYS_RATIO → mW
     *
     * 简化: PSYS 为电流型输出, 外部电阻 1kΩ 时:
     *   电压 = I_PSYS × 1kΩ
     *   I_PSYS = 电压 / 1000
     *   功率 = I_PSYS / ratio (ratio = 0.25uA/W 或 1uA/W)
     *
     * 对于 1uA/W 比率: 功率(W) = I_PSYS(uA)
     *   ADC_PSYS 8-bit, LSB=12mV → 最大 3.06V → 最大 3060uA → 3060W
     *
     *   实际功率(mW) = ADC_PSYS × 12mV / 1000Ω × 1000 / ratio_mw_per_ua
     *   若 ratio=1uA/W: power_mW = ADC_PSYS × 12
     */
    uint16_t adc_reg;
    _reg_read(BQ25710_REG_ADC_VBUS_PSYS, &adc_reg);
    uint8_t adc_psys = (uint8_t)(adc_reg & 0xFF);

    /* 读取 PSYS_RATIO */
    BQ25710_ChargeOption1_t opt1;
    _reg_read(BQ25710_REG_CHARGE_OPTION_1, &opt1.all);

    /* 功率 (mW): 1uA/W 时 power_mW = ADC_PSYS × 12
     *           0.25uA/W 时 power_mW = ADC_PSYS × 12 × 4 */
    int32_t power_mw = (int32_t)adc_psys * 12;
    if (opt1.maps.PSYS_RATIO == 0) {
        power_mw *= 4;  /* 0.25uA/W → 相当于 4x 换算 */
    }

    *power_mw_out = power_mw;
    return BQ25710_ERR_OK;
}

bq25710_err_t bq25710_psys_set_power_budget(int32_t max_power_mw)
{
    REG_ACCESS_CHECK();
    /* 功率预算: 当系统功率超过预算时动态降低充电电流
     * 本函数设置预算上限值, 实际调节需在主循环中调用 _psys_budget_check()
     */
    (void)max_power_mw;  /* 预算值存储在外部, 由上层周期调用 */
    return BQ25710_ERR_OK;
}

/* =========================================================================
 * 15.10 学习模式
 * ========================================================================= */

bq25710_err_t bq25710_learn_enter(void)
{
    REG_ACCESS_CHECK();
    return bq25710_set_mode(BQ25710_MODE_LEARN);
}

bq25710_err_t bq25710_learn_exit(void)
{
    REG_ACCESS_CHECK();
    return bq25710_set_mode(BQ25710_MODE_IDLE);
}

/**
 * @brief 内部: 库仑计数积分 — 周期性采样电流并累加电量
 * @param interval_ms 采样间隔 (ms)
 * @param duration_ms 总积分时间 (ms)
 * @param is_discharge 1=放电积分, 0=充电积分
 * @return 积分电量 (mAh)
 */
static float _coulomb_count(uint32_t interval_ms, uint32_t duration_ms,
                             uint8_t is_discharge)
{
    float total_mah = 0.0f;
    uint32_t elapsed = 0;

    while (elapsed < duration_ms) {
        /* 读取 IBAT ADC */
        uint16_t adc_reg;
        _reg_read(BQ25710_REG_ADC_IBAT, &adc_reg);
        BQ25710_ADCIBAT_t ibat;
        ibat.all = adc_reg;

        int32_t current_ma;
        if (is_discharge) {
            /* 放电: IDCHG, LSB 取决于 IBAT_GAIN
             *   16x: LSB=256mA, 8x: LSB=512mA
             */
            BQ25710_ChargeOption0_t opt0;
            _reg_read(BQ25710_REG_CHARGE_OPTION_0, &opt0.all);
            uint16_t lsb = (opt0.maps.IBAT_GAIN == 1) ? 512 : 256;  /* 0=16x(256mA), 1=8x(512mA) */
            current_ma = (int32_t)ibat.maps.ADC_IDCHG * lsb;
        } else {
            /* 充电: ICHG, LSB 取决于 IBAT_GAIN
             *   16x: LSB=64mA, 8x: LSB=128mA
             */
            BQ25710_ChargeOption0_t opt0;
            _reg_read(BQ25710_REG_CHARGE_OPTION_0, &opt0.all);
            uint16_t lsb = (opt0.maps.IBAT_GAIN == 1) ? 128 : 64;  /* 0=16x(64mA), 1=8x(128mA) */
            current_ma = (int32_t)ibat.maps.ADC_ICHG * lsb;
        }

        /* Q(mAh) = I(mA) × t(h) = I(mA) × dt(ms) / 3600000 */
        total_mah += (float)current_ma * (float)interval_ms / 3600000.0f;

        g_bq25710_ctx.delay_ms(interval_ms);
        elapsed += interval_ms;
    }

    return total_mah;
}

bq25710_err_t bq25710_learn_start_cycle(void)
{
    REG_ACCESS_CHECK();

    if (g_bq25710_ctx.mode != BQ25710_MODE_LEARN)
        return bq25710_learn_enter();

    bq25710_charge_ctx_t *ctx = &g_bq25710_ctx.charge;

    /* Phase 1: CC 充电 — 等待电池充满 */
    /* 切换到充电模式执行 CC+CV */
    _reg_write(BQ25710_REG_CHARGE_CURRENT,
               (uint16_t)(((uint32_t)ctx->params.charge_current_ma / 64U) << 6));

    BQ25710_ChargeOption0_t opt0;
    _reg_read(BQ25710_REG_CHARGE_OPTION_0, &opt0.all);
    opt0.maps.CHRG_INHIBIT = 0;
    _reg_write(BQ25710_REG_CHARGE_OPTION_0, opt0.all);

    /* 等待充电完成 (最长 6h) */
    uint32_t charge_timeout = 6 * 3600 * 1000;
    uint32_t charge_elapsed = 0;
    uint32_t poll_interval = 5000;  /* 5s 轮询 */

    while (charge_elapsed < charge_timeout) {
        g_bq25710_ctx.delay_ms(poll_interval);
        charge_elapsed += poll_interval;

        bq25710_adc_data_t adc;
        bq25710_adc_read_all(&adc);

        /* 充电完成判据: VBAT ≥ VREG 且 ICHG ≤ C/10 */
        if (adc.vbat_mv >= ctx->params.chg_voltage_mv * 99 / 100 &&
            adc.ichg_ma > 0 && adc.ichg_ma <= ctx->params.term_current_ma) {
            break;
        }
    }

    if (charge_elapsed >= charge_timeout)
        return BQ25710_ERR_TIMEOUT;

    /* Phase 2: 放电 — 库仑计数 */
    /* 禁止充电, 使能学习模式 (允许电池放电) */
    opt0.maps.CHRG_INHIBIT = 1;
    opt0.maps.EN_LEARN    = 1;
    _reg_write(BQ25710_REG_CHARGE_OPTION_0, opt0.all);

    /* 库仑计数放电积分: 10s 间隔, 最长 4h */
    float discharge_mah = _coulomb_count(10000, 4 * 3600 * 1000, 1);

    /* Phase 3: 退出学习模式, 存储容量 */
    opt0.maps.EN_LEARN = 0;
    _reg_write(BQ25710_REG_CHARGE_OPTION_0, opt0.all);

    g_bq25710_ctx.learn_capacity_mah = discharge_mah;
    g_bq25710_ctx.learn_complete     = 1;

    return BQ25710_ERR_OK;
}

bq25710_err_t bq25710_learn_get_capacity_mah(float *capacity_mah_out)
{
    NULL_CHECK(capacity_mah_out);
    if (!g_bq25710_ctx.learn_complete)
        return BQ25710_ERR_STATE;
    *capacity_mah_out = g_bq25710_ctx.learn_capacity_mah;
    return BQ25710_ERR_OK;
}

/* =========================================================================
 * ADC 监测
 * ========================================================================= */

/**
 * @brief 读取全部 8 通道 ADC 数据 (含动态增益补偿)
 * @param data 输出参数, ADC 数据结构体
 * @return BQ25710_ERR_OK / BQ25710_ERR_NULL_PTR
 */
bq25710_err_t bq25710_adc_read_all(bq25710_adc_data_t *data)
{
    REG_ACCESS_CHECK();
    NULL_CHECK(data);

    /* 读取当前增益设置 */
    BQ25710_ChargeOption0_t opt0;
    _reg_read(BQ25710_REG_CHARGE_OPTION_0, &opt0.all);
    uint8_t ibat_gain  = opt0.maps.IBAT_GAIN;   /* 0=16x, 1=8x  */
    uint8_t iadpt_gain = opt0.maps.IADPT_GAIN;  /* 0=20x, 1=40x */

    /* 读取全部 4 个 ADC 结果寄存器 */
    BQ25710_ADCVBUSPSYS_t      AdcVbusPsys;   // [0x23] VBUS 电压及 PSYS 功率读数
    BQ25710_ADCIBAT_t          AdcIbat;       // [0x24] 电池充/放电电流实时采样
    BQ25710_ADCIINCMPIN_t      AdcIinCmpin;   // [0x25] 输入电流及比较器输入读数
    BQ25710_ADCVSYSVBAT_t      AdcVsysVbat;   // [0x26] 系统电压及电池电压实时读数
    _reg_read(BQ25710_REG_ADC_VBUS_PSYS, &AdcVbusPsys.all);
    _reg_read(BQ25710_REG_ADC_IBAT,     &AdcIbat.all);
    _reg_read(BQ25710_REG_ADC_IIN_CMPIN,&AdcIinCmpin.all);
    _reg_read(BQ25710_REG_ADC_VSYS_VBAT,&AdcVsysVbat.all);

    /* VBUS: ADC_VBUS [15:8], LSB=64mV, 偏置 3200mV */
    data->vbus_mv = (uint16_t)(AdcVbusPsys.maps.ADC_VBUS * 64 + 3200);

    /* PSYS: ADC_PSYS [7:0], LSB=12mV → 需结合 PSYS_RATIO 换算功率 */
    {
        BQ25710_ChargeOption1_t opt1;
        _reg_read(BQ25710_REG_CHARGE_OPTION_1, &opt1.all);
        data->psys_mw = (int32_t)AdcVbusPsys.maps.ADC_PSYS * 12;
        if (opt1.maps.PSYS_RATIO == 0) data->psys_mw *= 4;
    }

    /* ICHG: ADC_ICHG [14:8], LSB 取决于 IBAT_GAIN
     *   16x(IBAT_GAIN=0): LSB=64mA
     *   8x(IBAT_GAIN=1):  LSB=128mA
     */
    data->ichg_ma = (int32_t)AdcIbat.maps.ADC_ICHG * (ibat_gain == 1 ? 128 : 64);

    /* IDCHG: ADC_IDCHG [6:0], LSB 取决于 IBAT_GAIN
     *   16x(IBAT_GAIN=0): LSB=256mA
     *   8x(IBAT_GAIN=1):  LSB=512mA
     */
    data->idchg_ma = (int32_t)AdcIbat.maps.ADC_IDCHG * (ibat_gain == 1 ? 512 : 256);

    /* IIN: ADC_IIN [15:8], LSB 取决于 IADPT_GAIN
     *   20x(IADPT_GAIN=0): LSB=50mA (默认)
     *   40x(IADPT_GAIN=1):  LSB=25mA
     */
    data->iin_ma = (int32_t)AdcIinCmpin.maps.ADC_IIN * (iadpt_gain == 1 ? 25 : 50);

    /* VSYS: ADC_VSYS [15:8], LSB=64mV, 偏置 2880mV */
    data->vsys_mv = (uint16_t)(AdcVsysVbat.maps.ADC_VSYS * 64 + 2880);

    /* VBAT: ADC_VBAT [7:0], LSB=64mV, 偏置 2880mV */
    data->vbat_mv = (uint16_t)(AdcVsysVbat.maps.ADC_VBAT * 64 + 2880);

    /* CMPIN: ADC_CMPIN [7:0], LSB=12mV */
    data->cmpin_mv = (uint16_t)(AdcIinCmpin.maps.ADC_CMPIN * 12);

    data->ibat_gain  = ibat_gain;
    data->iadpt_gain = iadpt_gain;
    data->timestamp_ms = g_bq25710_ctx.tick_ms;

    /* 更新内部缓存 */
    g_bq25710_ctx.adc_cache = *data;

    return BQ25710_ERR_OK;
}

/**
 * @brief 读取单个 ADC 通道
 * @param channel 通道选择: 0=VBAT, 1=VSYS, 2=ICHG, 3=IDCHG, 4=IIN, 5=PSYS, 6=VBUS, 7=CMPIN
 * @param value_mv_or_ma 输出参数, 电压(mV)或电流(mA)或功率(mW)
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM
 */
bq25710_err_t bq25710_adc_read_channel(uint8_t channel, int32_t *value_mv_or_ma)
{
    REG_ACCESS_CHECK();
    NULL_CHECK(value_mv_or_ma);
    PARAM_CHECK(channel <= 7);

    bq25710_adc_data_t data;
    bq25710_err_t ret = bq25710_adc_read_all(&data);
    if (ret != BQ25710_ERR_OK) return ret;

    switch (channel) 
    {
    case 0: *value_mv_or_ma = data.vbat_mv;  break;  /* VBAT */
    case 1: *value_mv_or_ma = data.vsys_mv;  break;  /* VSYS */
    case 2: *value_mv_or_ma = data.ichg_ma;  break;  /* ICHG */
    case 3: *value_mv_or_ma = data.idchg_ma; break;  /* IDCHG */
    case 4: *value_mv_or_ma = data.iin_ma;   break;  /* IIN */
    case 5: *value_mv_or_ma = data.psys_mw;  break;  /* PSYS */
    case 6: *value_mv_or_ma = data.vbus_mv;  break;  /* VBUS */
    case 7: *value_mv_or_ma = data.cmpin_mv; break;  /* CMPIN */
    default: return BQ25710_ERR_PARAM;
    }

    return BQ25710_ERR_OK;
}

/**
 * @brief 启动 ADC 连续转换模式
 * @param interval_ms 采样间隔 (ms), 硬件固定每秒一次, 此参数为软件轮询间隔
 * @return BQ25710_ERR_OK
 */
bq25710_err_t bq25710_adc_start_continuous(uint16_t interval_ms)
{
    REG_ACCESS_CHECK();
    (void)interval_ms;  /* 硬件固定每秒一次, 此参数为软件轮询间隔 (由上层使用) */

    BQ25710_ADCOption_t adc;
    _reg_read(BQ25710_REG_ADC_OPTION, &adc.all);
    adc.maps.ADC_CONV = 1;  /* 连续模式 */
    return _reg_write(BQ25710_REG_ADC_OPTION, adc.all);
}

/**
 * @brief 停止 ADC 连续转换, 切换回单次模式
 * @return BQ25710_ERR_OK
 */
bq25710_err_t bq25710_adc_stop_continuous(void)
{
    REG_ACCESS_CHECK();

    BQ25710_ADCOption_t adc;
    _reg_read(BQ25710_REG_ADC_OPTION, &adc.all);
    adc.maps.ADC_CONV = 0;  /* 切回单次模式 */
    return _reg_write(BQ25710_REG_ADC_OPTION, adc.all);
}

/* =========================================================================
 * 故障管理
 * ========================================================================= */

/**
 * @brief 综合故障检测 — 读取 ChargerStatus + ProchotStatus
 * @param mask 输出参数, 故障掩码结构体
 * @return BQ25710_ERR_OK / BQ25710_ERR_NULL_PTR
 */
bq25710_err_t bq25710_fault_check(bq25710_fault_mask_t *mask)
{
    REG_ACCESS_CHECK();
    NULL_CHECK(mask);

    memset(mask, 0, sizeof(bq25710_fault_mask_t));

    BQ25710_ChargerStatus_t    Status;        /**< [0x20] 反馈 AC、ICO、故障锁存信息 */
    _reg_read(BQ25710_REG_CHARGER_STATUS, &Status.all);

    mask->otg_uvp   = Status.maps.FAULT_OTG_UVP;
    mask->otg_ovp   = Status.maps.FAULT_OTG_OVP;
    mask->latch     = Status.maps.FAULT_LATCH;
    mask->sys_short = Status.maps.FAULT_SYS_SHORT;
    mask->sysovp    = Status.maps.SYSOVP_STAT;
    mask->acoc      = Status.maps.FAULT_ACOC;
    mask->batoc     = Status.maps.FAULT_BATOC;
    mask->acov      = Status.maps.FAULT_ACOV;

    BQ25710_ProchotStatus_t    ProchotStatus; /**< [0x21] 反馈 PROCHOT 详细触发原因 */
    _reg_read(BQ25710_REG_PROCHOT_STATUS, &ProchotStatus.all);

    mask->prochot_adapter_removal = ProchotStatus.maps.STAT_Adapter_Removal;
    mask->prochot_battery_removal = ProchotStatus.maps.STAT_Battery_Removal;
    mask->prochot_vsys            = ProchotStatus.maps.STAT_VSYS;
    mask->prochot_idchg           = ProchotStatus.maps.STAT_IDCHG;
    mask->prochot_inom            = ProchotStatus.maps.STAT_INOM;
    mask->prochot_icrit           = ProchotStatus.maps.STAT_ICRIT;
    mask->prochot_comp            = ProchotStatus.maps.STAT_COMP;
    mask->prochot_vdpm            = ProchotStatus.maps.STAT_VDPM;
    mask->prochot_vap_exit        = ProchotStatus.maps.STAT_EXIT_VAP;
    mask->prochot_vap_fail        = ProchotStatus.maps.STAT_VAP_FAIL;

    /* 更新内部缓存 */
    g_bq25710_ctx.fault_cache = *mask;

    return BQ25710_ERR_OK;
}

/**
 * @brief 清除所有故障锁存
 * @return BQ25710_ERR_OK
 */
bq25710_err_t bq25710_fault_clear_all(void)
{
    REG_ACCESS_CHECK();

    BQ25710_ChargerStatus_t    Status;        /**< [0x20] 反馈 AC、ICO、故障锁存信息 */
    _reg_read(BQ25710_REG_CHARGER_STATUS, &Status.all);
    Status.low_byte = 0;
    _reg_write(BQ25710_REG_CHARGER_STATUS, Status.all);

    BQ25710_ProchotStatus_t    ProchotStatus; /**< [0x21] 反馈 PROCHOT 详细触发原因 */
    _reg_read(BQ25710_REG_PROCHOT_STATUS, &ProchotStatus.all);
    ProchotStatus.all &= 0xFC00;
    ProchotStatus.maps.PROCHOT_CLEAR = 1;
    _reg_write(BQ25710_REG_PROCHOT_STATUS, ProchotStatus.all);

    return BQ25710_ERR_OK;
}

/**
 * @brief 获取活动故障的详细描述字符串
 * @param mask  故障掩码
 * @param buf   输出缓冲区
 * @param buf_size 缓冲区大小
 * @return 写入的字符串长度
 */
int bq25710_fault_get_detail(const bq25710_fault_mask_t *mask,
                             char *buf, int buf_size)
{
    if (!mask || !buf || buf_size <= 0) return 0;

    int pos = 0;
    int remain = buf_size;

    #define FAULT_APPEND(str) \
        do { \
            int n = snprintf(buf + pos, remain, "%s%s", (pos > 0 ? ", " : ""), str); \
            if (n > 0 && n < remain) { pos += n; remain -= n; } \
        } while (0)

    if (mask->acov)                     FAULT_APPEND("ACOV (输入过压)");
    if (mask->acoc)                     FAULT_APPEND("ACOC (输入过流)");
    if (mask->batoc)                    FAULT_APPEND("BATOC (电池放电过流)");
    if (mask->sysovp)                   FAULT_APPEND("SYSOVP (系统过压)");
    if (mask->sys_short)                FAULT_APPEND("SYS_SHORT (系统短路)");
    if (mask->otg_uvp)                  FAULT_APPEND("OTG_UVP (OTG欠压)");
    if (mask->otg_ovp)                  FAULT_APPEND("OTG_OVP (OTG过压)");
    if (mask->latch)                    FAULT_APPEND("LATCHOFF (强制闭锁)");
    if (mask->prochot_adapter_removal)  FAULT_APPEND("PROCHOT:适配器移除");
    if (mask->prochot_battery_removal)  FAULT_APPEND("PROCHOT:电池移除");
    if (mask->prochot_vsys)             FAULT_APPEND("PROCHOT:VSYS欠压");
    if (mask->prochot_idchg)            FAULT_APPEND("PROCHOT:放电过流");
    if (mask->prochot_inom)             FAULT_APPEND("PROCHOT:输入平均过流");
    if (mask->prochot_icrit)            FAULT_APPEND("PROCHOT:输入峰值过流");
    if (mask->prochot_comp)             FAULT_APPEND("PROCHOT:比较器");
    if (mask->prochot_vdpm)             FAULT_APPEND("PROCHOT:VDPM");
    if (mask->prochot_vap_exit)         FAULT_APPEND("PROCHOT:VAP退出");
    if (mask->prochot_vap_fail)         FAULT_APPEND("PROCHOT:VAP失败");

    #undef FAULT_APPEND

    if (pos == 0) 
    {
        snprintf(buf, buf_size, "无故障");
    }

    return pos;
}

/* =========================================================================
 * 看门狗管理
 * ========================================================================= */

/**
 * @brief 配置看门狗超时时间
 * @param timeout_sec 超时时间: 0=禁用, 5, 88, 175
 * @return BQ25710_ERR_OK / BQ25710_ERR_PARAM
 */
bq25710_err_t bq25710_wdt_config(bq25710_watchdog_t timeout_sec)
{
    REG_ACCESS_CHECK();

    if (timeout_sec == BQ25710_WDT_DISABLE) 
    {
        g_bq25710_ctx.wdt_timeout_ms = 0;
    } 
    else if (timeout_sec <= BQ25710_WDT_5S) 
    {
        g_bq25710_ctx.wdt_timeout_ms = 5000;
    } 
    else if (timeout_sec <= BQ25710_WDT_88S) 
    {
        g_bq25710_ctx.wdt_timeout_ms = 88000;
    } else 
    {
        g_bq25710_ctx.wdt_timeout_ms = 175000;
    }

    BQ25710_ChargeOption0_t    Option0;       /**< [0x12] 基础充电选项 */
    _reg_read(BQ25710_REG_CHARGE_OPTION_0, &Option0.all);
    Option0.maps.WDTMR_ADJ = timeout_sec;
    _reg_write(BQ25710_REG_CHARGE_OPTION_0, Option0.all);

    return BQ25710_ERR_OK;
}

/**
 * @brief 喂狗
 * 
 * @return bq25710_err_t 状态码
 */
bq25710_err_t bq25710_wdt_kick(void)
{
    REG_ACCESS_CHECK();

    /* 写 ChargeOption0 任意值会重置看门狗
     * 读取当前值再写回 (read-modify-write 会触发 SMBus Write-Word)
     */
    uint16_t opt0;
    _reg_read(BQ25710_REG_CHARGE_OPTION_0, &opt0);
    int8_t ret = _reg_write(BQ25710_REG_CHARGE_OPTION_0, opt0);

    g_bq25710_ctx.last_kick_ms = g_bq25710_ctx.tick_ms;
    return (ret == 0) ? BQ25710_ERR_OK : BQ25710_ERR_I2C;
}


/* =========================================================================
 * 自动检测
 * ========================================================================= */

/**
 * @brief 自动检测电池节数 (通过 CELL_BATPRESZ 引脚电压)
 * @param cells_out 输出参数, 检测到的节数 (1~4)
 * @return BQ25710_ERR_OK / BQ25710_ERR_BAT_MISSING
 */
bq25710_err_t bq25710_auto_detect_cells(battery_cell_count_t *cells_out)
{
    REG_ACCESS_CHECK();
    NULL_CHECK(cells_out);

    /* 通过 CELL_BATPRESZ 引脚电压判断节数:
     *   1S: 引脚电压 = 电池电压 × 1/1
     *   2S: 引脚电压 = 电池电压 × 1/2
     *   3S: 引脚电压 = 电池电压 × 1/3
     *   4S: 引脚电压 = 电池电压 × 1/4
     *
     * 实际通过 ADC_VBAT 读取电池电压, 配合默认 ChargeVoltage 推断节数:
     *   默认 VREG: 1S=4200mV, 2S=8400mV, 3S=12600mV, 4S=16800mV
     *   读取 VREG × VBAT 比例 → 节数
     */
    bq25710_adc_data_t adc;
    bq25710_adc_read_all(&adc);

    uint16_t vbat = adc.vbat_mv;

    if (vbat < 1000) 
    {
        *cells_out = BATTERY_CELLS_INVALID;
        return BQ25710_ERR_BAT_MISSING;
    }

    /* 读取默认 ChargeVoltage */
    BQ25710_MaxChargeVoltage_t MaxChargeVolt; /**< [0x15] 电池充电电压目标 */
    _reg_read(BQ25710_REG_MAX_CHARGE_VOLT, &MaxChargeVolt.all);
    uint16_t vreg_mv = (uint16_t)(((MaxChargeVolt.all >> 3) & 0xFFF) * BQ25710_CHG_VOLT_STEP);

    /* 按默认 VREG 推断节数 */
    if      (vreg_mv <= 5000)  *cells_out = BATTERY_CELLS_1S;
    else if (vreg_mv <= 10000) *cells_out = BATTERY_CELLS_2S;
    else if (vreg_mv <= 14000) *cells_out = BATTERY_CELLS_3S;
    else                       *cells_out = BATTERY_CELLS_4S;

    return BQ25710_ERR_OK;
}

/**
 * @brief 自动检测电池化学类型 (小电流充电观察电压平台)
 * @param cells     已知的电池节数
 * @param chem_out  输出参数, 检测到的化学类型
 * @return BQ25710_ERR_OK / BQ25710_ERR_BAT_MISSING
 */
bq25710_err_t bq25710_auto_detect_chemistry(battery_cell_count_t cells,
                                            battery_chemistry_t *chem_out)
{
    REG_ACCESS_CHECK();
    NULL_CHECK(chem_out);
    IS_BATTERY_CELLS(cells);

    /* 化学类型检测: 写小电流充电, 观察电压平台
     *   LiFePO4: 单节平台 ~3.2V → 4S ≈ 12.8V
     *   NMC:     单节平台 ~3.7V → 4S ≈ 14.8V
     *
     * 方法: 设 256mA 充电, 等待 30s, 读取 VBAT, 判断平台
     */
    BQ25710_ChargeCurrent_t    ChargeCurrent; /**< [0x14] 电池充电电流目标值 */
    _reg_read(BQ25710_REG_CHARGE_CURRENT, &ChargeCurrent.all);

    /* reg = (256 / 64) << 6 = 4 << 6 = 0x0100 */
    _reg_write(BQ25710_REG_CHARGE_CURRENT, 0x0100);

    /* 使能充电 */
    BQ25710_ChargeOption0_t    Option0;       /**< [0x12] 基础充电选项 */
    _reg_read(BQ25710_REG_CHARGE_OPTION_0, &Option0.all);
    uint16_t orig_inhibit = Option0.maps.CHRG_INHIBIT;
    Option0.maps.CHRG_INHIBIT = 0;
    _reg_write(BQ25710_REG_CHARGE_OPTION_0, Option0.all);

    /* 等待 30 秒让电压稳定 */
    uint32_t wait_ms = 30000;
    while (wait_ms > 0) {
        g_bq25710_ctx.delay_ms(1000);
        wait_ms -= 1000;
    }

    /* 读取电池电压 */
    bq25710_adc_data_t adc;
    bq25710_adc_read_all(&adc);

    /* 恢复充电电流和禁止状态 */
    _reg_write(BQ25710_REG_CHARGE_CURRENT, ChargeCurrent.all);
    Option0.maps.CHRG_INHIBIT = orig_inhibit;
    _reg_write(BQ25710_REG_CHARGE_OPTION_0, Option0.all);

    /* 判断: 单节电压 > 3.5V → NMC, ≤ 3.5V → LiFePO4 */
    uint16_t vbat_per_cell = adc.vbat_mv / cells;

    if (vbat_per_cell > 3500) 
    {
        *chem_out = BATTERY_CHEM_NMC;
    } 
    else 
    {
        *chem_out = BATTERY_CHEM_LIFEPO4;
    }

    return BQ25710_ERR_OK;
}

/* =========================================================================
 * 系统信息
 * ========================================================================= */

static const struct {
    uint8_t  reg;
    const char *name;
} _reg_map[] = {
    { BQ25710_REG_CHARGE_OPTION_0,  "ChargeOption0"   },
    { BQ25710_REG_CHARGE_OPTION_1,  "ChargeOption1"   },
    { BQ25710_REG_CHARGE_OPTION_2,  "ChargeOption2"   },
    { BQ25710_REG_CHARGE_OPTION_3,  "ChargeOption3"   },
    { BQ25710_REG_PROCHOT_OPTION_0, "ProchotOption0"  },
    { BQ25710_REG_PROCHOT_OPTION_1, "ProchotOption1"  },
    { BQ25710_REG_ADC_OPTION,       "ADCOption"       },
    { BQ25710_REG_CHARGE_CURRENT,   "ChargeCurrent"   },
    { BQ25710_REG_MAX_CHARGE_VOLT,  "MaxChargeVoltage"},
    { BQ25710_REG_INPUT_VOLTAGE,    "InputVoltage"    },
    { BQ25710_REG_MIN_SYS_VOLTAGE,  "MinSystemVoltage"},
    { BQ25710_REG_IN_CURR_HOST,     "IIN_HOST"        },
    { BQ25710_REG_OTG_VOLTAGE,      "OTGVoltage"      },
    { BQ25710_REG_OTG_CURRENT,      "OTGCurrent"      },
    { BQ25710_REG_CHARGER_STATUS,   "ChargerStatus"   },
    { BQ25710_REG_PROCHOT_STATUS,   "ProchotStatus"   },
    { BQ25710_REG_IN_CURR_DPM,      "IIN_DPM (RO)"    },
    { BQ25710_REG_ADC_VBUS_PSYS,    "ADC_VBUS_PSYS"   },
    { BQ25710_REG_ADC_IBAT,         "ADC_IBAT"        },
    { BQ25710_REG_ADC_IIN_CMPIN,    "ADC_IIN_CMPIN"   },
    { BQ25710_REG_ADC_VSYS_VBAT,    "ADC_VSYS_VBAT"   },
    { BQ25710_REG_MANUFACTURE_ID,   "ManufactureID"   },
    { BQ25710_REG_DEVICE_ID,        "DeviceID"        },
};

/**
 * @brief 打印全部寄存器
 */
void bq25710_dump_all_registers(void)
{
    if (!g_bq25710_ctx.initialized) return;

    printf("\n============ BQ25710 Register Dump ============\n");
    printf("| Hex    | 15 14 13 12 11 10 09 08  07 06 05 04 03 02 01 00\n");
    printf("------------------------------------------------------------------------\n");

    int num = sizeof(_reg_map) / sizeof(_reg_map[0]);
    for (int i = 0; i < num; i++) {
        uint16_t val;
        if (_reg_read(_reg_map[i].reg, &val) != 0) {
            printf("%-20s | ERROR\n", _reg_map[i].name);
            continue;
        }

        printf("%-20s | 0x%04X | ", _reg_map[i].name, val);
        for (int j = 15; j >= 0; j--) {
            printf("%c ", (val & (1 << j)) ? '1' : '0');
        }
        printf("\n");
    }
    printf("================================================\n");
}

/**
 * @brief 获取综合系统状态
 * @param status 输出参数, 系统状态结构体
 * @return BQ25710_ERR_OK / BQ25710_ERR_NULL_PTR
 */
bq25710_err_t bq25710_get_system_status(bq25710_system_status_t *status)
{
    REG_ACCESS_CHECK();
    NULL_CHECK(status);

    memset(status, 0, sizeof(bq25710_system_status_t));

    /* 模式与阶段 */
    status->mode      = g_bq25710_ctx.mode;
    status->chg_stage = g_bq25710_ctx.charge.stage;

    /* 适配器 / 电池 */
    BQ25710_ChargerStatus_t    Status;        /**< [0x20] 反馈 AC、ICO、故障锁存信息 */
    _reg_read(BQ25710_REG_CHARGER_STATUS, &Status.all);

    status->adapter_present = Status.maps.AC_STAT;
    status->is_charging     = Status.maps.IN_FCHRG || Status.maps.IN_PCHRG;
    status->is_otg          = Status.maps.IN_OTG;
    status->is_vap          = Status.maps.IN_VAP;
    status->ico_done        = Status.maps.ICO_DONE;

    /* PTM 状态 */
    BQ25710_ChargeOption1_t    Option1;       /**< [0x30] 增益与硬件参数设置 */
    _reg_read(BQ25710_REG_CHARGE_OPTION_1, &Option1.all);
    status->is_ptm = Option1.maps.EN_PTM;

    /* 电池存在检测: ChargerStatus 不直接提供, 通过 ADC_VBAT 判断 */
    bq25710_adc_read_all(&status->adc);
    status->battery_present = (status->adc.vbat_mv > 1000) ? 1 : 0;

    /* 电池参数 */
    status->batt_params = &g_bq25710_ctx.charge.params;

    /* 充电设定 */
    BQ25710_ChargeCurrent_t    ChargeCurrent; /**< [0x14] 电池充电电流目标值 */
    _reg_read(BQ25710_REG_CHARGE_CURRENT, &ChargeCurrent.all);
    status->charge_current_set_ma = (uint16_t)(((ChargeCurrent.all >> 6) & 0x7F) * 64);

    BQ25710_MaxChargeVoltage_t MaxChargeVolt; /**< [0x15] 电池充电电压目标 */
    _reg_read(BQ25710_REG_MAX_CHARGE_VOLT, &MaxChargeVolt.all);
    status->charge_voltage_set_mv = (uint16_t)(((MaxChargeVolt.all >> 3) & 0xFFF) * 8);

    /* 输入电流限制 */
    BQ25710_IN_CURR_HOST_t     InCurrHost;    /**< [0x3F] 适配器端输入电流限制 */
    _reg_read(BQ25710_REG_IN_CURR_HOST, &InCurrHost.all);
    status->input_current_limit_ma = (uint16_t)(((InCurrHost.all >> 8) & 0x7F) * 50);

    /* 故障 */
    bq25710_fault_check(&status->fault);

    /* 检查是否有活动故障 */
    uint16_t *f = (uint16_t *)&status->fault;
    status->fault_active = (*f != 0) ? 1 : 0;

    /* 运行时间 */
    status->uptime_ms      = g_bq25710_ctx.tick_ms;
    status->chg_elapsed_ms = g_bq25710_ctx.charge.total_elapsed_ms;
    status->wdt_timeout_ms = g_bq25710_ctx.wdt_timeout_ms;
    status->last_kick_ms   = g_bq25710_ctx.last_kick_ms;

    return BQ25710_ERR_OK;
}

/**
 * @brief 打印格式化的 ASCII 状态报告
 */
void bq25710_print_status_report(void)
{
    if (!g_bq25710_ctx.initialized) {
        printf("BQ25710: 驱动未初始化\n");
        return;
    }

    bq25710_system_status_t st;
    bq25710_get_system_status(&st);

    printf("\n============ BQ25710 System Status ============\n");
    printf("  Mode:          %s\n", bq25710_mode_names_en[st.mode]);
    printf("  Charge Stage:  %s\n", _chg_stage_names_en[st.chg_stage]);

    printf("  AC Adapter:    %s\n", st.adapter_present ? "ONLINE" : "OFFLINE");
    printf("  Battery:       %s\n", st.battery_present ? "PRESENT" : "MISSING");
    printf("  Charging:      %s\n", st.is_charging ? "YES" : "NO");
    printf("  OTG Active:    %s\n", st.is_otg ? "YES" : "NO");
    printf("  VAP Active:    %s\n", st.is_vap ? "YES" : "NO");
    printf("  PTM Active:    %s\n", st.is_ptm ? "YES" : "NO");
    printf("  ICO Done:      %s\n", st.ico_done ? "YES" : "NO");

    if (st.battery_present && (st.batt_params != NULL)) {
        printf("  Chemistry:     %s, %dS\n",
               st.batt_params->chemistry_name,
               battery_cells_value(st.batt_params->cells));
    }

    printf("  --- ADC Readings ---\n");
    printf("  VBUS:  %5u mV\n", st.adc.vbus_mv);
    printf("  VSYS:  %5u mV\n", st.adc.vsys_mv);
    printf("  VBAT:  %5u mV\n", st.adc.vbat_mv);
    printf("  ICHG:  %5d mA\n", (int)st.adc.ichg_ma);
    printf("  IDCHG: %5d mA\n", (int)st.adc.idchg_ma);
    printf("  IIN:   %5d mA\n", (int)st.adc.iin_ma);
    printf("  PSYS:  %5d mW\n", (int)st.adc.psys_mw);
    printf("  CMPIN: %5u mV\n", st.adc.cmpin_mv);

    printf("  --- Settings ---\n");
    printf("  VREG Set:    %5u mV\n", st.charge_voltage_set_mv);
    printf("  ICHG Set:    %5u mA\n", st.charge_current_set_ma);
    printf("  IIN Limit:   %5u mA\n", st.input_current_limit_ma);
    printf("  WDT Timeout: %5u ms\n", st.wdt_timeout_ms);

    printf("  --- Faults ---\n");
    if (st.fault_active) {
        char fault_str[256];
        bq25710_fault_get_detail(&st.fault, fault_str, sizeof(fault_str));
        printf("  ACTIVE: %s\n", fault_str);
    } else {
        printf("  CLEAR (no faults)\n");
    }

    printf("  Uptime:       %u ms\n", st.uptime_ms);
    printf("================================================\n");
}
